### ISSUE TITLE
Port 9000 is already in use

### ISSUE THREAD

**Issue by romainromss** [symfony/panther#10]
Hello, 

On my mac the port 9000 is already in use.

![capture d ecran 2018-04-05 a 15 18 00](https://user-images.githubusercontent.com/24546909/38368192-edf01ffa-38e4-11e8-8006-dd3fcdf81b71.png)

and this is my code 

![capture d ecran 2018-04-05 a 15 21 09](https://user-images.githubusercontent.com/24546909/38368211-fe9cf6fc-38e4-11e8-81f3-6c76a828f5d0.png)

Have you ever had this problem? is there a way to change it?

**Comment by dunglas** [comment]
Not yet, but a PR is welcome. A better strategy would be to iterate until a free port is available.

**Comment by romainromss** [comment]
With pleasure, but I'm in formation, I don't have much time.

**Comment by dunglas** [comment]
No worry :)

**Comment by LegendOfGIT** [comment]
@romainromss
How does your static function createPanthereClient look like.
The reason I ask is that there is an optional parameter in the PanthereWebManager constructor which allows to choose a port for a panthere client.

**Comment by mablae** [comment]
I was able to use another port like this: 
```php
        self::startWebServer(null, '127.0.0.1', 7000);
        if (null === self::$pantherClient) {
            $client = self::$pantherClient = Client::createChromeClient(null, ['--headless', 'window-size=1600,900', '--disable-gpu', '--no-sandbox'], [], self::$baseUri);
        }
```

**Comment by sauvajaune** [comment]
Hi,
I juste get the same problem... Forgive my english ,  I'm french...
So the problem comes from your php versions which is running in background ( for my case it was php 7.1 and for my prject I was using php 7.3) 

Solution : 

"brew services list"

then

"brew services stop php@7.1 " (replace by your version to stop)

**Comment by sqrt-1764** [comment]
@sauvajaune: I think you are barking up the wrong tree.
PHP itself uses no Ports and also is no Service. Port 9000 is used e.g. by xDebug which is a Debugger for PHP. Apparently you kill the service that provides PHP for your webserver-instance. (I have no mac, so this is only an educated guess)

The solution lies in the environment-varables.
In the Readme.md search for "PANTHER_WEB_SERVER_PORT". With this Variable you can control the port Panther uses. If you set it to something other than 9000 the error will vanish.

**Comment by SnakeWhisperer** [comment]
> 
> 
> @sauvajaune: I think you are barking up the wrong tree.
> PHP itself uses no Ports and also is no Service. Port 9000 is used e.g. by xDebug which is a Debugger for PHP. Apparently you kill the service that provides PHP for your webserver-instance. (I have no mac, so this is only an educated guess)
> 
> The solution lies in the environment-varables.
> In the Readme.md search for "PANTHER_WEB_SERVER_PORT". With this Variable you can control the port Panther uses. If you set it to something other than 9000 the error will vanish.

Hi. I'm having this same problem, but the error I get says "The port 9515 is already in use" and my 'PANTHER_WEB_SERVER_PORT' variable is set to 9800. Do you know what I can do here?

**Comment by AcelisWeaven** [comment]
@SnakeWhisperer Hi, I'm having the exact same issue frequently since the latest update even though I use `PANTHER_WEB_SERVER_PORT` with another value. Have you found a solution?

**Comment by MichaelBrauner** [comment]
You actually can do it like that: 

```php
        static::createPantherClient(array_replace(static::$defaultOptions, [
            'webServerDir' => $this->getPublicDir(),
            'port' => 9081
        ]));
```
