### ISSUE TITLE
Symfony syntax not working ?

### ISSUE THREAD

**Issue by BLKKKBVSIK** [symfony/panther#11]
Hello, this code is working fine with Symfony crawler, but it's not working anymore with panthere

`$crawler->filter('div:contains("This value should not be blank")')`

Here is the error:
`WebDriver\Exception\InvalidSelectorException: invalid selector: An invalid or illegal selector was specified`

**Comment by arthurchipdean** [comment]
I haven't used this project at all so take this with a grain of salt. 

I'm guessing this project only supports valid CSS selectors though. `contains` is a jQuery selector.  If you try using that in `document.querySelectorAll` it will throw an error.

**Comment by dunglas** [comment]
@arthurchipdean you're right.
I wasn't aware that Symfony supports this syntax, we can add support for it using a JS polyfill.

**Comment by qferr** [comment]
@dunglas Do you know when you support jQuery selector ? Thanks

**Comment by dunglas** [comment]
AFAIK, nobody is working on it. But maybe that a better move would be to deprecate support for ˋcontains` is Symfony CssSelector as this selector will not be standardized. WDYT? ping @symfony/deciders

**Comment by lyrixx** [comment]
I never us this filter, and this is not part of the spec, I'm fine for deprecating it

**Comment by fabpot** [comment]
Deprecating non-standard features works for me. We should probably check that not too many people would be affected by this change though.
