### ISSUE TITLE
Secure web server [question]

### ISSUE THREAD

**Issue by leevigraham** [symfony/panther#114]
Is it possible to use a secure web server for the panther client?

I can see that the scheme is hardcoded here: https://github.com/symfony/panther/blob/master/src/PantherTestCaseTrait.php#L114

The reason for the request is that I'm using dunglas/DunglasAngularCsrfBundle with the secure cookie option. I noticed while trying to run tests the cookie was not set when using the http:// scheme.

**Comment by dunglas** [comment]
If you use your own web server, this code will not be called, so yes, it works (or it’s a bug)

**Comment by stof** [comment]
Don't use the `startWebServer` method of Panther (which uses the PHP builtin webserver which does not do HTTPS). Instead, configure your client to connect to a webserver managed externally (using nginx, Apache, or whatever else)

**Comment by dunglas** [comment]
You can also use `startWebServer` with the `hostname` option as stated here: https://github.com/symfony/panther/issues/115#issuecomment-427957331

It definitely deserves a documentation entry.

**Comment by dunglas** [comment]
We should provide a new option here https://github.com/symfony/panther/blob/master/src/PantherTestCaseTrait.php#L123 to skip starting the built-in web server.
