### ISSUE TITLE
Dev-tool always open

### ISSUE THREAD

**Issue by DamienLevGemy** [symfony/panther#168]
Hello !

when i launch the test running PANTHER_NO_HEADLESS=1 ./bin/phpunit on my symfony 4.2 project, i can see than chrome open with the dev tool, and this makes my tests not working well because of my bootstrap 4 navbar. Any possibility to configure it ?

**Comment by WaRioO** [comment]
I see that i have to configure it via the phpunit.xml.dist and this lane : 
<server name="PANTHER_CHROME_ARGUMENTS" value=""/>

but what to write in "value" ? i don't find it anywhere :(

**Comment by ghostika** [comment]
set in `config/test/web_profiler.yaml`  the `toolbar` to `false` ( it should be `false` by default) or if you use the `dev` env, then in the `config/dev/web_profiler.yaml`.

**Comment by vitoo** [comment]
He is talking about chrome dev tool, not symfony web profiler

I've got the same issue

you can do : `$client->manage()->window()->maximize()` to maximize the windows

**Comment by vitoo** [comment]
i find a workaround 
This open chrome with dev tool open
`Client::createChromeClient(null,  null, [], self::$baseUri);
`
This not
`Client::createChromeClient(null,  [], [], self::$baseUri);`

So here is my BaseTestcase.php

```php
<?php


namespace App\Tests;

use Facebook\WebDriver\WebDriver;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Panther\Client as PantherClient;
use Symfony\Component\Panther\PantherTestCase;
use Symfony\Component\Panther\Client;


abstract class BaseTestCase extends PantherTestCase
{
    /**
     * @var WebDriver
     */
    protected  $client;

    protected static $started = false;

    protected function setUp()
    {
        $this->client = static::createPantherClient(['external_base_uri' => 'http://bogestionhoraire.local/']);
        $this->client->manage()->window()->maximize();
        $this->client->manage()->timeouts()->implicitlyWait(10);
        static::bootKernel();
    }

    protected static function createPantherClient(array $options = [], array $kernelOptions = []): PantherClient
    {
        self::startWebServer($options);
        if (null === self::$pantherClient) {
            self::$pantherClient = Client::createChromeClient(null,  [], [], self::$baseUri);
        }

        if (\is_a(self::class, KernelTestCase::class, true)) {
            static::bootKernel($kernelOptions);
        }

        return self::$pantherClient;
    }
}
```

And my ExampleTest.php


namespace App\Tests;


use Facebook\WebDriver\WebDriverBy;

```php

class UserTest extends BaseTestCase
{

    public function testLogin()
    {
        $this->client->get('');
        $this->assertContains(
            'Login',
            $this->client->getPageSource()
        );

   }

}
```

**Comment by vitoo** [comment]
Hi @dunglas maybe we should change the createChromeClient parameters to avoid opening chrome with de dev-tool ?

Like i explained in my previous message

Thanks

**Comment by stof** [comment]
Opening the dev tools when you don't run in headless mode (as part of the default set of arguments) is actually done on purpose.

**Comment by tienvx** [comment]
@stof Do you think is it a good idea to add another environment variable for devtools? e.g. PANTHER_OPEN_DEVTOOLS

**Comment by OskarStark** [comment]
@stof if you want to take screenshot and define a size for a window, a lot of this space is used by the dev tools....

**Comment by dunglas** [comment]
Screenshots should work in headless mode (with dev tools closed).

**Comment by OskarStark** [comment]
Yes but to debug for example which size should be used for the final screenshot it's hard to find out. At least an option to deactivate the dev tools 🛠 would be 👍🏻

**Comment by ctouma-placedestendances** [comment]
Sorry, I know this discussion is old, we can easily disable the inspector (devtool) with `PANTHER_DEVTOOLS=0`
