### ISSUE TITLE
CreatePlatformSocket() returned an error: The requested service provider could not be loaded or initialized. (0x277A) [1556555424.762]

### ISSUE THREAD

**Issue by san-ratul** [symfony/panther#188]
after integrating with laravel I am getting this error is there any way to resolve this problem?
![Screenshot (2)](https://user-images.githubusercontent.com/15213657/56911410-a2e16b00-6ace-11e9-99bb-b3375ba02e44.png)

**Comment by dunglas** [comment]
It looks like a ChromeDriver error. Are you able to run ChromeDriver manually?
