### ISSUE TITLE
[Question] Downloaded file

### ISSUE THREAD

**Issue by gponty** [symfony/panther#189]
Hi,

How to get content of a downloaded file ?
by example when submit a form, i tried with :

`$this->client->getResponse()->getContent();`

But : HttpFoundation Response object is not available when using WebDriver.

Thank you

**Comment by dunglas** [comment]
Downloading iles is not supported by the WebDriver protocol. However you can use hacks like those ones:

* https://github.com/facebook/php-webdriver/issues/536#issuecomment-371776323
* https://stackoverflow.com/a/47943109/1352334
