### ISSUE TITLE
Using Chromedriver in a remote server

### ISSUE THREAD

**Issue by martinbertinat** [symfony/panther#190]
Hi! Sorry if this is more a support-type question.

Is it possible to install chromedriver in a remote server so from my main server run my web crawlers using this remote chromedriver (possible on digitalocean).

I cannot find a way to define the host in which is installed chromedriver (if it is possible)

Thank you!

**Comment by Fneufneu** [comment]
going to the same problem and the only solution i found is:
```php
$client = \Symfony\Component\Panther\Client::createChromeClient(null, null, ['host' => '192.168.0.10']);
```
and modify src/ProcessManager/ChromeManager.php line 46 to
```php
if (!$this->process->isRunning() && '127.0.0.1' == $this->options['host']) {
```

**Comment by dunglas** [comment]
Currently it's not possible, but a patch is welcome!

That being said, wouldn't it better in your case to use a Selenium server instead of ChromeDriver? This is already supported:

```php
$customSeleniumClient = Client::createSeleniumClient('http://127.0.0.1:4444/wd/hub', null, 'https://example.com'); // Create a custom Selenium client
```

**Comment by martinbertinat** [comment]
Thank you @dunglas!

It's working with Selenium now!

I'm closing this.
