### ISSUE TITLE
Using proxy

### ISSUE THREAD

**Issue by hectorprats** [symfony/panther#192]
Hello, I would like to test how my website works through proxies from different countries. How can I select proxy in chromeclient? I can not find the way.

**Comment by Loooooouuuuu** [comment]
Hi ! I couldn't find anything in the documentation. I found this way : 

```
$client = Client::createChromeClient(null, [
             '--proxy-server=socks://127.0.0.1:9050',
             '--headless',
             "--disable-gpu",
        ]);
```

which seems to work. It would be better if we could manipulate `$capabilities` in ChromeManager.php in the start() function.

**Comment by hectorprats** [comment]
thanks, it works :-)

**Comment by dunglas** [comment]
Would one you be interested in updating the README to explain this? Thanks!

**Comment by Loooooouuuuu** [comment]
@dunglas My english isn't perfect, but I will try !

**Comment by nouaman1996** [comment]
Hi i was wondering if it works for you guys when the proxy need an authentification? i cant make it work, thanks

**Comment by stof** [comment]
@nouaman1996 AFAICT, the chrome binary does not support configuring the proxy credentials through the CLI.

**Comment by nouaman1996** [comment]
@stof  Hi, so any idea how i can use chromeClient or even seleniumClient with a proxy authentification? thanks
