### ISSUE TITLE
`GLIBC_2.14' not found 

### ISSUE THREAD

**Issue by sam-zed** [symfony/panther#193]
Hello 
so wanted to try panther 
Installed Symfony on cPanel environment then installed panther
without luck, the error is attached as the following image :
![screenshot-brave amberlly co-2019 05 20-08-27-00](https://user-images.githubusercontent.com/1163627/58003770-63a8a780-7ad9-11e9-9156-5197bbee6b63.png)

**Comment by dunglas** [comment]
As stated by the error message, Chromedriver required the GNU libc, as well as Chrome or Chromium. Install them on the server.
