### ISSUE TITLE
[Question] CSRF and Sessions

### ISSUE THREAD

**Issue by fabstei** [symfony/panther#195]
I'm starting to write some functional tests with Panther and I love it.

But I'm unsure how to work around CSRF: I can't (*) disable it for the tests, but enabling it means that I can't submit any forms because the CSRF fails as there is only the mock_file enabled for tests - works fine for functional tests without a mock browser, not so much with a real browser.

Enabling "real" sessions for the test environment does not work either, as I run into the "headers already sent" issue [the mock_file is fixing](https://github.com/symfony/symfony/issues/25615).

I'm stuck on this now for an unhealthy amount of time already. Any pointers toward a good solution?

(*) My authentication system (that is being tested) is tied to the CSRF being enabled. Even after removing the dependency and disabling CSRF for tests I get errors on forms - my app is just not set up to work without CSRF enabled.

**Comment by dunglas** [comment]
According to my testing, enabling real sessions work for Panther, but not for the `WebTestCase`.

A possible solution would be to create a new env for Panther.

**Comment by vsilvestre-accenture** [comment]
I do have the same problem, I've tried to apply your fix so now panther env is used but it doesn't change a lot. There's any extra step to fix this problem ?
