### ISSUE TITLE
Le terme «PANTHER_NO_HEADLESS=1» n'est pas reconnu comme nom d'applet de commande

### ISSUE THREAD

**Issue by Orou-dev** [symfony/panther#196]
Hi everyone
thx for reading this and to take the time to answer it...If this post isnt at the good place I apologize and feel free to move it 

Im new to symfony even newer to panther. im trying to use panther for the 1st time. I followed the doc here : 
[https://symfony.com/blog/introducing-symfony-panther-a-browser-testing-and-web-scrapping-library-for-php](url)

Everything works fine until this part where I have to run PANTHER_NO_HEADLESS=1 ./bin/phpunit. Ive got an error saying : 

PS C:\Users\pifmo\Desktop\Siblu Stage\pantherTest> PANTHER_NO_HEADLESS=1 ./bin/phpunit
PANTHER_NO_HEADLESS=1: Le terme «PANTHER_NO_HEADLESS=1» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. 
Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 1
+ PANTHER_NO_HEADLESS=1=1 ./bin/phpunit
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PANTHER_NO_HEADLESS=1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I tried several things to fix it but nothing works. I tried to change my env variable in windows, see below: 
![image](https://user-images.githubusercontent.com/43614913/58863818-d60db000-86b3-11e9-9876-cfc68a57b7c4.png)

I tried to run it in powershell and cmd as admin didnt worked either. Same with my IDE terminal

my config : 
Window 10 
symfony 4.3 
Apache 2.4.37 Port 80- PHP 7.2.14
MySQL 5.7.24 
PHP 5.6.40 for CLI (Command-Line Interface)

Any idea where it come from and how to fix it ? 

thanks for helping

**Comment by Orou-dev** [comment]
up 

probleme solved

**Comment by stof** [comment]
Putting temporary env variables inline in the beginning of the command is the syntax supported by `sh` shells. The Windows CLI does not support that. On Windows, you will need to set the env variable before running the command (and resetting it after if you want to actually have the same behavior of defining it only for this command).

**Comment by Orou-dev** [comment]
thx for your answer ! thats what Ive done. Setting the command as env variable worked, no need to write the commande again in the windows CLI
