### ISSUE TITLE
[RFC] Embed Symfony server

### ISSUE THREAD

**Issue by Pierstoval** [symfony/panther#199]
Instead of using `php -S` as a server, and since Panther already ships `chromedriver`, why not also ship the `symfony` CLI in order to have a much more powerful webserver, which would support HTTP/2, TLS and all good things the CLI carries?

**Comment by dunglas** [comment]
As Symfony CLI isn't open source, I'm not sure that it's a good idea to ship it. Also it will require to tag a new version of Panther every time a new version of `symfony` is released.

An alternative approach could be to keep the current code as is, but if `symfony` is in the path, then use it. WDYT?

**Comment by Pierstoval** [comment]
Totally agree :+1:

**Comment by dunglas** [comment]
Another idea could be to add a new argument to the `symfony` command to run Panther (phpunit) and set the appropriate environment variables to use the web server provided by the tool instead of the PHP one. /cc @fabpot

**Comment by Pierstoval** [comment]
I think this is too case-specific, and for now, focusing on having a nice web server seems like the easiest way, especially if it's both transparent and customizable by the end user (for instance, on my project, I run `symfony serve -d` and use `external_base_uri` on my tests to tell Panther to use it, it's pretty straightforward, so having Panther do it would be simpler to me).

Additionnally, the Symfony CLI is not open-source, so if Panther has to change, the CLI integration must change too, and we cannot maintain it. Having Symfony CLI as a way to start the webserver instead of making it run phpunit & panther by itself seems like a better approach for maintenance.
