### ISSUE TITLE
"Chrome could not start (or has crashed) after 5 seconds."

### ISSUE THREAD

**Issue by developer-bro** [symfony/panther#208]
I got this error on production server. Im running on AWS ubuntu 18.04 instance.

request.CRITICAL: Uncaught PHP Exception RuntimeException: "Chrome could not start (or has crashed) after 5 seconds." at /vendor/symfony/panther/src/ProcessManager/WebServerReadinessProbeTrait.php:51)"} []

**Comment by dunglas** [comment]
Probably a duplicate of https://github.com/symfony/panther/issues/200. Can you try if increasing the timeout as described in this issue helps?

**Comment by developer-bro** [comment]
No luck increasing the timeout.

same error again.

Uncaught PHP Exception RuntimeException: "Chrome could not start (or has crashed) after 30 seconds."

**Comment by lyrixx** [comment]
Could you try master, and tell me what error message you get?

**Comment by vasilvestre** [comment]
Same situation, full message is (RuntimeException: Could not connect to chrome after 5 seconds (Invalid or missing HTTP status line.).
May not be related
