### ISSUE TITLE
executeScript and load new data

### ISSUE THREAD

**Issue by acamenhas** [symfony/panther#212]
Hi all, i'm very new here.

I need to execute a javascript that will fire an ajax event on the page, that will load some new elements on the page, and finally catch them.

The fist part is ok, with:
`$client->executeScript("document.querySelector('div.test').click();");
`

Now i need to wait 2-3 seconds and them grab the "new crawler html".

How can i do those 2 final steps?
Thank you!

**Comment by acamenhas** [comment]
I found the solution, just sleep for 2seconds and then filter que crawler content.

I'm going to close this.

**Comment by trbsi** [comment]
Just in case someone needs help. I had a case where I had a form and a button. I filled a form and clicked on button. Then new page opened. I needed to get data from new page. This is how I did it:
```
$url = "https://someurl";
$crawler = $this->client->request('GET', $url); //$this->client is Symfony\Component\Panther\Client
$form = $crawler->filter('#Form1')->form();
$form->setValues([
      'someField' => 12183,
]);
//This is where I executed JS script to click on a button
$client->executeScript("document.querySelector('#btnSpecial').click()");
//wait for new element on new page to appear
$this->client->waitFor('#results');
//refresh crawler so you can crawl newly loaded page
$crawler = $client->refreshCrawler();
//now crawl new page
```
