### ISSUE TITLE
Example to Gitlab

### ISSUE THREAD

**Issue by andreybolonin** [symfony/panther#229]
Any examples to run Panther on Gitlab CI ?

<img width="1145" alt="Screen Shot 2019-09-03 at 8 33 22 AM" src="https://user-images.githubusercontent.com/2576509/64146433-a2166800-ce25-11e9-924d-f5bce8a87db1.png">

My .gitlab-ci.yml
`image: ubuntu:bionic

services:
- postgres:11

variables:
  POSTGRES_PASSWORD: root
  POSTGRES_USER: root
  POSTGRES_DB: vipaero
#  PANTHER_CHROME_DRIVER_BINARY: /usr/lib/chromium/chromedriver
  PANTHER_NO_SANDBOX: 1

before_script:
- apt-get update
- apt-get install software-properties-common -y
- ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
#- add-apt-repository ppa:ondrej/php -y
- apt-get install curl wget php php-cli php7.2 php7.2-common php7.2-curl php7.2-pgsql php7.2-mysql php7.2-intl php7.2-gd php7.2-xml php7.2-opcache php7.2-mbstring php7.2-zip libfontconfig1 fontconfig libxrender-dev libfreetype6 libxrender1 chromium-browser chromium-chromedriver zlib1g-dev xvfb -y -qq
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php composer-setup.php --install-dir=/usr/local/bin --filename=composer
- php -r "unlink('composer-setup.php');"
- composer
- chromedriver --version
- php -v
- php -m
- composer install --ignore-platform-reqs
- bin/console doctrine:schema:update --force
- bin/console doctrine:schema:validate
- bin/console doctrine:fixtures:load

stages:
- test
- deploy

test:
  script:
  - vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no src/ --rules=@Symfony
  - vendor/bin/phpstan analyse src --level=1
  - vendor/bin/simple-phpunit`

**Comment by Bersman** [comment]
This is working for me:
My .gitlab-ci.yml file:
`image: php:7.2-fpm-alpine
cache:
  paths:
    - vendor/
before_script:
  - apk add --no-cache chromium chromium-chromedriver zlib-dev
  - export PANTHER_CHROME_DRIVER_BINARY="/usr/lib/chromium/chromedriver"
  - export PANTHER_NO_SANDBOX=1
  - export PANTHER_WEB_SERVER_PORT=9800
  - docker-php-ext-install zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

test:
  script:
    - chromedriver --version
    - ./bin/phpunit --colors=never`

**Comment by andreybolonin** [comment]
@Bersman thx
