### ISSUE TITLE
Operation timed out after 30001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by qferr** [symfony/panther#235]
Hello,

I have a lot of functional tests and when I launch phpunit, an errors occurs: 

> Operation timed out after 30001 milliseconds with 0 bytes received.

When I launch test one by one or I comment some tests, everything is ok.

For details, all tests are executed into a docker container. I don't have change the panther configuration.

Thanks for you help.

**Comment by romaricdrigon** [comment]
Hello,
How many tests do you have?
I'm having the same error since earlier today. I suspect it appears after ~50 test sessions.

**Comment by romaricdrigon** [comment]
I'm using Chrome, and I'm now sure it is related to how long my test suite is taking. It is crashing at about 3 minutes, no mater which tests I run.

Thank you for the suggestion, I will look into :)

**Comment by Pierstoval** [comment]
Isn't it related to the fact that the `Process` component has a default timeout when launching the web server or the chromium instance?

**Comment by qferr** [comment]
Hello,

@romaricdrigon, I have more than 20 tests in my test suite. But I'm using the @dataProvider feature which increase the number of tests, and the number of sessions.

@Pierstoval I have already increased the timeout value of the remote web driver, there was no effect.

I think you can reproduce this issue like that:

```php
public function testSomething()
{
    $client = static::createPantherClient();
   
    for ($i = 1; $i <= 30; $i++) {
        $client->request('GET', '/');
    }
}
```

Thanks for you help

**Comment by romaricdrigon** [comment]
I tried increasing it (both `timeout` and `idleTimeout`), no change.
I suspect Chrome has a memory leak or alike, and eventually crash later. Something similar to this issue: https://github.com/elgalu/docker-selenium/issues/20#issuecomment-521382058

**Comment by qferr** [comment]
Yes, I saw a lot of issues before to create this one. I tried to increase the /dev/shm, no success. Is it related to the docker environment ? :thinking:

I wanted to use Selenium instead, but it has the same problem.

**Comment by romaricdrigon** [comment]
I could reproduce the crash with that piece of code:
```
    public function test_crash()
    {
        $this->client = static::createPantherClient();

        // 100 does not crash, 200 does
        for ($i = 1; $i <= 200; $i++) {
            $this->client->request('GET', '/');

            $this->assertPageContains('e');
        }
    }
```

It crashes both inside or outside Docker, with different Chrome versions (Chromium 76 or Chrome 77).

**Comment by romaricdrigon** [comment]
I will. I will try to remove JS and elements one by one from my page, and we will see.

Weird thing is that Chrome dev tools does not raise any warning about my page, everything looks pretty light...

**Comment by qferr** [comment]
@Pierstoval I removed all JS, the same error occured

**Comment by romaricdrigon** [comment]
Removing JS or images from the page helps, but when I add more tests, it fails again.

Right now I'm trying to use `/ tmp` instead of `/dev/shm` on Docker, it seems to work (to a point?).
@qferr you an try it too by setting `PANTHER_CHROME_ARGUMENTS='--disable-dev-shm-usage'`

**Comment by domis86** [comment]
@romaricdrigon can you try increase available memory (or swap etc) and try again?
If works in such case then it is memory related problem

**Comment by romaricdrigon** [comment]
Moving from 2 GB to 4 Gb of memory, and from 1 GB of swap to 2 did not helped.
`--disable-dev-shm-usage` seems to help only a little bit, too. There's an issue with Chrome, not quite Panther, and for now I don't know how to handle it :S

**Comment by qferr** [comment]
@romaricdrigon I tried your suggestion, it did not work. My chrome arguments are:

```php
array:5 [
  0 => "--headless"
  1 => "--window-size=1200,1100"
  2 => "--disable-gpu"
  3 => "--no-sandbox"
  4 => "--disable-dev-shm-usage"
]
```

I'm using the chromedriver 2.37.544315 and chromium 73.0.3683.75 that running on Debian 9.9

**Comment by Pierstoval** [comment]
Is there a way to completely disable the cache? Maybe multiple requests will create multiple cache instances that blow up the container 😕

**Comment by romaricdrigon** [comment]
Which cache are you referring to?

I found a workaround for now, which is to restart everything after/before each "big" test scenario. 
In example:
```php
// at the end of your test, with $client
$client->quit(true);
self::stopWebServer();

$client = static::createPantherClient();
```

That's clearly suboptimal, but since I suspect bug is inside Chrome/Chromium or chromedriver, there's not much to do but to wait for an update.

**Comment by Pierstoval** [comment]
I mean client cache. Maybe chromium is storing some cache in your container and the cache causes the issue?

**Comment by romaricdrigon** [comment]
I suppose that’s mostly memory/swap. Hence restarting it clears everything.
Really I don’t quite know how to debug Chrome further.
-- 
Romaric Drigon

**Comment by qferr** [comment]
@romaricdrigon I have already tried this workaround but running tests is very very slow because Panther will create a new webserver and start the client for each test.

**Comment by Pierstoval** [comment]
@qferr A solution could be to start the web server & chrome instance before the test suite and keep them persistent.

**Comment by romaricdrigon** [comment]
How come? Chrome will crash, and that's it.
Btw, Panther does not support running over an already existing Chrome instance (though it should be trivial to implement).

**Comment by Pierstoval** [comment]
The whole thing comes from the `ChromeManager` that automatically starts a process with the chromedriver binary. We should provide some extension point or something that would allow overriding this behavior and customize `start()` and `quit()` methods

**Comment by romaricdrigon** [comment]
Yesterday I had an epiphany: in my case, it is not Chrome which was crashing, but PHP webserver. For some reason, it hangs the connection, making Chrome freeze on a blank page. I'm using PHP 7.3.10, and increasing `memory_limit` did not help.
Moving to Apache solved all issues, and as a bonus, it made tests a little bit faster.

**Comment by Pierstoval** [comment]
I tested this yesterday with the code examples and with many tests and I couldn't reproduce even with 200 tests, but it's probably because I'm using the symfony webserver to run the app before running the test suite 😄

**Comment by romaricdrigon** [comment]
Indeed!

**Comment by romaricdrigon** [comment]
Webserver crashing could be related to this: https://jolicode.com/blog/you-may-have-memory-leaking-from-php-7-and-symfony-tests
Bottom line: there's a PHP bug causing a memory leak while rebooting Symfony kernel. Fingers crossed so it gets fixed soon!

**Comment by petermandersvin** [comment]
I am running into similar issues.  One of my tests is passing if I run it separate, but failing if I run the full tests with the noted error. I am using dataProviders to test a bulk at once. My application is running in docker.

**Comment by qferr** [comment]
Hello. 

I have resolved my problem :muscle: 

Before to launch a test suite, I start an external web server in background with a custom script:

```
$ bin/server start
$ bin/phpunit
$ bin/server stop
```
Output:
```
Start the web server http://localhost:9080
Waiting for the web server is running...
The web server is running
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
..........
OK (10 tests, 32 assertions)
The web server is stopped
```
Don't forget to set `PANTHER_EXTERNAL_BASE_URI=http://localhost:9080`


The `server.sh` use a [PHP Built-in web server](https://www.php.net/manual/en/features.commandline.webserver.php). 

Short example:
```
#!/bin/bash
...
APP_ENV=$APP_ENV php -dvariables_order=EGPCS -S "PANTHER_EXTERNAL_BASE_URI" -t public/ &> $logFile &
...
```

I tried to create a `ServerCommand` and use the `Process` service but the test suite also timed out. I think that `Process` is not able to maintain a php process running :thinking: 

Hope it help !

Best regards

**Comment by Hitcounter2** [comment]
https://lnkr.fun/2f405d7 Got the final answer
