### ISSUE TITLE
Update waitFor() to accept either css selector or xpath expression?

### ISSUE THREAD

**Issue by webignition** [symfony/panther#238]
At present, `waitFor()` accepts as the first argument a CSS selector. This inherently rules out identifying the element to be waited for using an xpath expression.

We can modify the internal behaviour of this method such that it accepts either a CSS selector or xpath expression without affecting any valid current usage.

An xpath expression will always start with a single forward slash whereas a valid CSS selector will never do so, therefore we can reliably determine the locator type and either call `WebDriverBy::cssSelector()` or `WebDriverBy::xpath()` as needed.

Such a change would "break" things for existing use cases where a CSS selector with a leading forward slash is used, however I'm not sure that counts as valid usage that cannot be broken.

**Comment by webignition** [comment]
See PR #239 for a proposed implementation.

**Comment by nusje2000** [comment]
You could do the following:
```
$client->wait()->until(
    WebDriverExpectedCondition::presenceOfElementLocated(
