### ISSUE TITLE
Chromium-browser install on ubuntu 19.10

### ISSUE THREAD

**Issue by andreybolonin** [symfony/panther#252]
Any ideas how to fix this on ubuntu eoan ?

<img width="646" alt="Screen Shot 2019-10-25 at 1 56 49 PM" src="https://user-images.githubusercontent.com/2576509/67566026-75991100-f72f-11e9-9b8e-62f8cb1aea0e.png">

**Comment by domis86** [comment]
Can you paste the command that was executed?

**Comment by andreybolonin** [comment]
```apt-get install curl wget php7.3 php7.3-common php7.3-curl php7.3-pgsql php7.3-intl php7.3-gd php7.3-xml php7.3-opcache php7.3-mbstring php7.3-zip git zlib1g-dev chromium-browser chromium-chromedriver -y -qq```

**Comment by dunglas** [comment]
This isn’t related to Panther, please report to Ubuntu directly.
