### ISSUE TITLE
0.6.0 depends on symfony/framework-bundle, package lacking in composer.json require section

### ISSUE THREAD

**Issue by webignition** [symfony/panther#256]
PR #254 (included in release 0.6.0) added `src/WebTestAssertionsTrait.php` which uses `Symfony\Bundle\FrameworkBundle\Test\WebTestAssertionsTrait`.

When upgrading a project of mine to use panther 0.6.0, phpstan crashed when linting due to:

`Trait 'Symfony\Bundle\FrameworkBundle\Test\WebTestAssertionsTrait' not found in [file]`

`symfony/framework-bundle` is present in the `require-dev` section of `composer.json` but not the `require` section.

Projects using `symfony/panther` as a direct dependency (not a dev dependency) will not pull in the `symfony/framework-bundle` dependency unless otherwise explicitly required. Having to explicitly require the dependencies of a dependency isn't the right way to do things.

A file in `src` now directly depends on a file within test namespace of `symfony/framework-bundle`. For things to work nicely, panther itself should declare a direct dependency on `symfony/framework-bundle` (not just a dev dependency).

Solutions that I can see:

1. move the current `symfony/framework-bundle` requirement from `require-dev` to `require`
2. find another means of making the changes applied in #254 work without a direct dependency on `symfony/framework-bundle`

Solution 1 feels wrong to me (or at least not fully right). Having a file in `src` depend on a file in the test namespace of `symfony/framework-bundle` seems ... messy. But this does seem to be the more pragmatic solution.

Solution 2 could be achieved by factoring out `WebTestAssertionsTrait` from `symfony/framework-bundle` into a separate package upon which both `symfony/panther` and `symfony/framework-bundle` could depend. This seems like a heck of a lot of work and involves many parties to be achieved. Perhaps ideal but not realistic.

@dunglas What are your thoughts on this?

**Comment by dunglas** [comment]
This trait shouldn't be imported `symfony/framework-bundle` isn't installed: https://github.com/symfony/panther/blob/master/src/PantherTestCase.php#L57-L59

Do you have a strack trace to share showing when this trait is required?

**Comment by webignition** [comment]
@dunglas You're right, the trait isn't imported if `symfony/framework-bundle` isn't installed.

The issue is not a matter when executing code (my project depends on `symfony/panther` and functional tests for the project run just fine), the issue is with phpstan crashing due to a `use` statement referencing a class that does not exist.

Or at least that was the case, it doesn't seem to want to occur now. I'll try to get things failing agani, perhaps I misunderstood something!

**Comment by webignition** [comment]
Hmm ... phpstan was behaving oddly, seemingly analyzing some files in `/vendor` for some reason. Odd but no longer happening.

Not sure what was going on there but now I realise what was happening I can see how I raised this issue in error. Sorry to have bothered you.

**Comment by dunglas** [comment]
No problems, thanks for investigating!

**Comment by webignition** [comment]
I managed to get things failing again locally. Had to clone the repo to a different local directory for the issue to start presenting itself again.

The error relates to the fact that I have a functional test which extends `PantherTestCase` for a project that doesn't use `symfony/framework-bundle` in any manner.

The error:

```
./vendor/bin/phpstan analyse tests/Functional/AbstractTestCase.php --level=7 --memory-limit=4G
Note: Using configuration file /home/jon/www/lib/webignition/foo/phpstan.neon.
PHPStan crashed in the previous run probably because of excessive memory consumption.
It consumed around 10 MB of memory.


To avoid this issue, allow to use more memory with the --memory-limit option.
PHP Fatal error:  Trait 'Symfony\Bundle\FrameworkBundle\Test\WebTestAssertionsTrait' not found in /home/jon/www/lib/webignition/foo/vendor/symfony/panther/src/WebTestAssertionsTrait.php on line 29
```

My best guess is that this is by no means an issue with panther and that phpstan is analyzing `PantherTestCase` when it should not be.

**Comment by webignition** [comment]
I can workaround this issue locally by requiring symfony/framework-bundle prior to executing phpstan and then removing symfony/framework-bundle prior to running tests that extend `PantherTestCase`.

Not ideal but it gets builds passing ...

**Comment by guillaume-perreal** [comment]
We have the same error here. Oddly, it fails in CI but works locally...

BTW, phpstan has to analyze the files in vendor to do proper type-checking.
