### ISSUE TITLE
DevToolsActivePort file doesn't exist.

### ISSUE THREAD

**Issue by vincentchalamon** [symfony/panther#260]
Adding `--remote-debugging-port=9222` option fixes this chrome issue.

Sources: https://github.com/heroku/heroku-buildpack-google-chrome/issues/46#issuecomment-475365061

**Comment by vincentchalamon** [comment]
Already fixed on latest version of Chrome (apparently)

**Comment by G0URAB** [comment]
> 
> 
> Adding `--remote-debugging-port=9222` option fixes this chrome issue.
> 
> Sources: [heroku/heroku-buildpack-google-chrome#46 (comment)](https://github.com/heroku/heroku-buildpack-google-chrome/issues/46#issuecomment-475365061)

Is there any environment variable to do that? Like this  PANTHER_WEB_SERVER_PORT=9222?

**Comment by adxl** [comment]
@shubaivanqbee Have you found a solution to this problem?
