### ISSUE TITLE
Accessing a javascript global variable.

### ISSUE THREAD

**Issue by franksteinberg** [symfony/panther#264]
Is it possible to use Panther to create a php variable from the contents of a page's global javascript variable?

Example: There is a page that has a global variable, `var data` that contains an array of table records. I can go to that page in my browser and `console.log(data)` or `console.table(data)` and get the values I'm expecting.

What I'd like to be able to do is load this page from within a PHP script using Panther, and store the contents of the Javascript variable `data` into a php variable `$data` for use in the script.

Is this possible?

**Comment by domis86** [comment]
Yes - try like this:

```
        $client = \Symfony\Component\Panther\Client::createChromeClient();
        $client->request('GET', 'https://api-platform.com/');

        // execute some js code:
        $result = $client->executeScript('
            return "it workz " + document.location;
        ');
        dump($result);
```
it should display:
```
"it workz https://api-platform.com/"
```

**Comment by deepakbasnal** [comment]
@domis86 You're a lifesaver. Thanks a lot
