### ISSUE TITLE
Symfony 5

### ISSUE THREAD

**Issue by michaelKaefer** [symfony/panther#270]
More an info than an issue: The dependency facebook/webdriver is not compatible with Symfony 5 until now so we cannot use Panther in Symfony 5 😭😭😭.

<code>facebook/webdriver 1.7.1 requires symfony/process ^2.8 || ^3.1 || ^4.0 -> no matching package found.</code>

**Comment by cmen** [comment]
A temporary solution is to use the dev version of php-webdriver until the next release. 
In your project :
```
composer require facebook/webdriver:^1.8@dev --dev
```

**Comment by liaosankai** [comment]
It's working that add `"facebook/webdriver": "^1.8@dev"`  to `replace` property of `composer.json` before next release.

```
{
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*",
        "facebook/webdriver": "^1.8@dev"
    },
}
```

**Comment by massimo-me** [comment]
Another way! If you don't use any `symfony/process ~5.` features

By default, if you starting a new Symfony 5 project in your `composer.json`all your dependencies are forced to version `5`. 

From this configuration :
```
#composer.json
"extra": {
    "symfony": {
       "allow-contrib": false,
        "require": "5.0.*"
    }
}
```

If you remove this configuration you can force your `symfony/process` to `4.4.*`, and you can install panther quickly.

```
"symfony/panther": "^0.6.0",
"symfony/process": "4.4.*",
```

**Comment by ymc-sise** [comment]
They changed the package name. For me it solved the line:

```
composer require php-webdriver/webdriver:dev-master --dev
```

**Comment by PReimers** [comment]
I just installed Panther on a fresh Symfony 5 and everything went well.

Panther is using the new `php-webdriver/webdriver` package since version `0.6.1` 😉

**Comment by michaelKaefer** [comment]
@PReimers Thank you for the info!
