### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by gabrielspiteri-highlight** [symfony/panther#304]
Hi 

I am trying to use the panther module inside a docker container. However when I try to instantiate a ChromeClient I am getting the following error message: **session not created: This version of ChromeDriver only supports Chrome version 80**

It would seem that `apt-get install chromium` installs **version 73** which could be why I am mis-matching with the ChromeDriver. 

Anything I can do to get chrome/chromium version 80 installed?

Thanks

**Comment by gabrielspiteri-highlight** [comment]
Update: managed to install version 80 of chrome using the following in my docker file:

# Install chrome, required for the symfony/panther library
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/chrome.deb
RUN dpkg -i /tmp/chrome.deb || apt-get install -yf
RUN rm /tmp/chrome.deb

**Comment by dunglas** [comment]
Thanks for the update! Could you open a PR to update the Dockerfile example we provide?

**Comment by gabrielspiteri-highlight** [comment]
@dunglas sure ... my only concern with the code i used is that say google issues a new release for chrome. My docker command would install the latest version which might lead to another mismatch between driver and chrome. Maybe we should lock it down to the version specific deb file that matches the current driver we use?

**Comment by gabrielspiteri-highlight** [comment]
@dunglas I have opened PR as requested. #306

**Comment by webignition** [comment]
@gabrielspiteri-highlight Regarding the chrome/chrome-driver potential incompatibility problem, this can be addressed by always installing both the latest chrome and the latest chrome-driver.

In #306 a URL to download chrome 80 is used. As you said, this will require updating as new chrome releases are made.

Use https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb to get the current release regardless of version number.

To ensure that chrome-driver matches, `cd` to `symfony/panther/chromedriver-bin` and run `update.sh` from that directory. This will retrieve the latest chrome driver. How exactly this is to be achieved in the example docker image I can't be certain but I'm guessing you get easily figure that one out.

**Comment by Kolvin** [comment]
Looks like the PR #306 has gone stale, would be great to get it merged to save folk time in the future :)

I have the following working

```dockerfile
FROM php:7.4-fpm
###
RUN apt-get update && apt-get install -y libappindicator1 fonts-liberation \
    && wget https://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/chrome.deb \
    && dpkg -i /tmp/chrome.deb; apt-get -fy install \
    && rm /tmp/chrome.deb \
    && cd vendor/symfony/panther/chromedriver-bin/ && ./update.sh
```

**Comment by dbrekelmans** [comment]
For this use-case you can use https://github.com/dbrekelmans/browser-driver-installer already.

Just run the `bdi browser:google-chrome` command and it will install the correct driver for you ;)
Let panther know where to find the driver you just installed with the env var `PANTHER_CHROME_DRIVER_BINARY`

**Comment by jprivet-dev** [comment]
Thanks @gabrielspiteri-highlight !

I had the same issue **Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 85**

Currently I'am using a Docker `debian:stretch-slim` image. This image contains the version 73 of Chrome and doesn't match with the version of ChromeDriver : 

I completed my code with yours (and remove the original `chromium` and `docker-php-ext-install zip` in my case): 

```
FROM debian:stretch-slim

...

###> Panther & Chrome ###

# @see https://github.com/symfony/panther#docker-integration
RUN apt-get update && apt-get install -y libzip-dev zlib1g-dev
ENV PANTHER_NO_SANDBOX 1
ENV PANTHER_CHROME_ARGUMENTS='--disable-dev-shm-usage'

# @see https://github.com/symfony/panther/issues/304#issuecomment-590396321
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/chrome.deb
RUN dpkg -i /tmp/chrome.deb || apt-get install -yf
RUN rm /tmp/chrome.deb

###< Panther & Chrome ###
...
```

This code has installed the latest version of Chrome:

```
Unpacking google-chrome-stable (87.0.4280.66-1) ...
```

After starting my containers and installing my project with my command `$ make install` (for composer, encore, etc), I used the 2 following commands to update ChromeDriver:

```
$ cd cd vendor/symfony/panther/chromedriver-bin/
$ ./update.sh 
Downloading ChromeDriver version 87.0.4280.20...
Done.
```

After that I was able to run my tests with Panther without errors :tada:
