### ISSUE TITLE
ChromeDriver remote url

### ISSUE THREAD

**Issue by versh23** [symfony/panther#312]
Now it not possbile to use chrome driver running on remote host. ChromeManager require binary path.

Is it possbile to make PR to add enviroment variable like a PANTHER_CHROME_REMOTE_HOST and use it here 

https://github.com/symfony/panther/blob/master/src/ProcessManager/ChromeManager.php#L45 ?

**Comment by versh23** [comment]
ping @dunglas

**Comment by dunglas** [comment]
You can use the `SeleniumManager` for that.
