### ISSUE TITLE
Constant usage in Trait broken

### ISSUE THREAD

**Issue by fetzi** [symfony/panther#317]
When I'm not using the `PantherTestCase` base class and am just using the `PantherTestCaseTrait` I receive the following error:

```
Error: Undefined class constant 'CHROME'
```

The problem arises because all constants inside the trait are accessed with `self::`. Using the class name instead should fix the problem.

**Comment by symfonyaml** [comment]
I created a PR using late static binding https://github.com/symfony/panther/pull/320
