### ISSUE TITLE
Panther only supports getting normalized text

### ISSUE THREAD

**Issue by iceuponfire** [symfony/panther#325]
since the symfony 4.4.6 update i get the "Panther only supports getting normalized text" when running tests.

Maybe it could be related to https://github.com/symfony/symfony/pull/34151 ??

**Comment by lsdlp** [comment]
Hello same issue here. i have this error on my test "Panther only supports getting normalized text" when running tests." since the symfony 4.4.6 update

**Comment by raphaChoquet** [comment]
I agree. The problem seem to come from this [release](https://github.com/symfony/dom-crawler/compare/v4.4.5...v4.4.6). 
Onconstraint, they change : 
`$crawler->text()` by `$crawler->text(null, false)` however in the crawler if you pass false as second parameter, this throw the exception "Panther only supports getting normalized text" : 
```
public function text(string $default = null, bool $normalizeWhitespace = true): string
{
    if (!$normalizeWhitespace) {
        throw new \InvalidArgumentException('Panther only supports getting normalized text.');
    }
    [...]
}
```

**Comment by iceuponfire** [comment]
![image](https://user-images.githubusercontent.com/23210888/77918263-ea064c00-729b-11ea-8f6c-438eab10fb69.png)

dom-crawler seem to send false as the second argument?

**Comment by iceuponfire** [comment]
https://github.com/symfony/symfony/pull/35899
https://github.com/symfony/symfony/commit/ff2c362195db857238c543952ed54843030cba1d
