### ISSUE TITLE
Could not start chrome (or it crashed) after 30 seconds.

### ISSUE THREAD

**Issue by phenoengine** [symfony/panther#333]
Hey! 
Seems like duplicated but I cant solve the issue. 
Starting with firefox driver also causes `Could not start firefox (or it crashed) after 30 seconds.`
Also tries to increase $timeout to 60 secs inside `WebServerReadinessProbeTrait.php`, still no luck.

Server has enough resources 4 cores 16 gb ram.
Composer dependency` "symfony/panther": "^0.7.1"`

Any ideas?

**Comment by huraji** [comment]
Same here. Did you solve it?

**Comment by vjandrea** [comment]
Issue is still relevant, updated Chromedriver and Chrome on Windows 10 but the tests won't start:
```
RuntimeException : Could not start chrome (or it crashed) after 30 seconds.
 C:\Users\dev\project\vendor\symfony\panther\src\ProcessManager\WebServerReadinessProbeTrait.php:51
 C:\Users\dev\project\vendor\symfony\panther\src\ProcessManager\ChromeManager.php:49
 C:\Users\dev\project\vendor\symfony\panther\src\Client.php:97
 C:\Users\dev\project\vendor\symfony\panther\src\Client.php:344
 C:\Users\dev\project\vendor\symfony\panther\src\Client.php:248
 C:\Users\dev\project\tests\Panther\CheckPantherTest.php:12
```

Could it be because chromedriver runs at 32 bits ?
**Chrome**: 83.0.4103.116 (Official Build) (64-bit)
**ChromeDriver**: 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416})

**Comment by huraji** [comment]
So in my case, I solved updating the drivers from the vendor folder.

`cd vendor/symfony/panther/chromedriver-bin/`
`./update.sh`

That was it.

**Comment by vjandrea** [comment]
Thanks @huraji , that's what I did and to be sure I updated chromedriver manually too, unfortunately it keeps failing on the same line.

**Comment by abdulmanan7** [comment]
same issue here

**Comment by tarlepp** [comment]
I'm having the same issue, running that `update.sh` didn't help.

**Comment by xitude** [comment]
I ran the `update.sh` but nothing I feel like im missing something.

**Comment by dunglas** [comment]
We need to finish this to improve this: https://github.com/symfony/panther/pull/358/

In the meantime, be sure that the Chromedriver version you use is compatible with the installed Chrome (or Chromium) version. You can use the `PANTHER_CHROME_DRIVER_BINARY` environment variable to point to a local Chromedriver binary.

**Comment by igor-mobapps** [comment]
I never used Panther, this is my first time and I'm getting the same problem ***Could not start chrome (or it crashed) after 30 seconds***, I tried the possible solution mentioned by @dunglas, but I was not successful, did I forget something?

**Running in local environment**
OS: Windows 10 Pro
Version: 20.04

**Panther version**
"symfony / panther": "^ 0.7.1"

**Local ChromeDriver**
$ ChromeDriver -v
ChromeDriver 85.0.4183.87

**panther ChromeDriver**
./update.sh
Downloading ChromeDriver version 85.0.4183.87 ...
Done.

**Chrome browser version**
Chrome version 85.0.4183.102 (Official version) 64 bits


**Code used**
````
        $client = \Symfony\Component\Panther\Client::createChromeClient();
        $response = $client->request('GET', 'https://api-platform.com');
        echo $response->html();
````

**Comment by gabrielspiteri-highlight** [comment]
Experiencing same issue on windows here ... same code on on linux (debian) machine ... with different chromedriver  obviously works fine.

**Comment by gabrielspiteri-highlight** [comment]
Guys just noticed that when you run update.sh you get the .exe driver named as chromedriver_win32.exe ... you need to rename that to chromedriver.exe since refer to: \Symfony\Component\Panther\ProcessManager\ChromeManager::findChromeDriverBinary

**Comment by gabrielspiteri-highlight** [comment]
The issue then moves to next part of \Symfony\Component\Panther\ProcessManager\WebServerReadinessProbeTrait::waitUntilReady

Giving the error: Could not connect to chrome after 30 seconds (fopen(http://127.0.0.1:9515/status): failed to open stream: Failed to parse address "0")."

However if I execute the chromedriver.exe myself manually then the status endpoint answers back correctly. So i think something is blocking the Process class to start chromedriver even tho its reports it as started.

**Comment by gabrielspiteri-highlight** [comment]
Ok so the above seem to be due to a bug introduced in php 7.4.10 ... reference here: https://github.com/symfony/symfony/issues/38081
and here https://github.com/php/php-src/pull/6104
