### ISSUE TITLE
Panther fails on Curl certificate validation on readiness trait  

### ISSUE THREAD

**Issue by benrcole** [symfony/panther#335]
Hi

It doesn't seem possible to use Panther without valid ssl certs. Whilst the environment variable switch can tell chrome to ignore certificate errors, `WebServerReadinessTrait::waitUntilReady` generates a curl client that is fails due to invalid certificates. 

Switching out

`$client = HttpClient::create(['timeout' => $timeout]);`

for

`$client = HttpClient::create(['timeout' => $timeout, 'verify_host' => false, 'verify_peer' => false]);`

enables me to test with Panther but this doesn't seem achievable via config, or am I missing something?

Ben

**Comment by wickedOne** [comment]
hi ben,

now that [this pr](https://github.com/symfony/panther/pull/370) is merged, you can pass additional capabilities to the panther client like this:

```php
$client = static::createPantherClient(
  [
    'external_base_uri' => 'https://my.site.test',
    'browser' => 'firefox',
  ], 
  [],
  [
    'acceptInsecureCerts' => true,
  ]
);
```

**Comment by pscheit** [comment]
`acceptInsecureCerts` didnt work for me but:

```php
            managerOptions: [
                'host' => 'http://selenium:4444/wd/hub',
                'capabilities' => DesiredCapabilities::chrome()
                    ->setCapability('goog:loggingPrefs', ['browser' => 'ALL'])
                    ->setCapability(WebDriverCapabilityType::ACCEPT_SSL_CERTS, true)
                ,
            ],
```

did
