### ISSUE TITLE
cannot test assert for series of pages

### ISSUE THREAD

**Issue by adityarai** [symfony/panther#338]
I'm trying to click on a link after logging in to dashboard, which will eventually open up another page inside dashboard and search for assert text contains. These are all normal http request/response page reload and not ajax. Is there a solution to test multiple urls which are not ajaxified? 

``<?php

namespace App\Tests\Controller;

use Symfony\Component\Panther\PantherTestCase;

class SecurityControllerTest extends PantherTestCase
{
    public function testCustomerRoleAfterLogin()
    {
        $client = static::createPantherClient();

        $client->request('GET', '/');

        $client->submitForm('Log In', [
            'username' => 'asd@gmail.com',
            'password' => 'asd123'
        ]);

        $client->request('GET', '/dashboard/index');
        $client->waitFor('#main-menu-sidebar-wrapper .settings');
        $this->assertSelectorTextContains('#main-menu-sidebar-wrapper .settings', 'Settings');
        $client->clickLink('#main-menu-sidebar-wrapper .settings');

        $client->request('GET', '/dashboard/settings');
        $client->waitFor('#editCustomerSettings span');
        $this->assertSelectorTextContains('#editCustomerSettings span', 'Customer Settings');

    }
}
``

**Comment by domis86** [comment]
So whats the error? :)
On which line?

**Comment by adityarai** [comment]
I'm trying to click on a link after logging in to dashboard, which will eventually open up another page inside dashboard and search for assert text contains.

**Comment by adityarai** [comment]
after logging in, it stops in  $client->waitFor('#main-menu-sidebar-wrapper .settings');

**Comment by domis86** [comment]
Can you wait few seconds  (sleep) before  that "waitFor" call and make screenshot?

```
        $client->request('GET', '/dashboard/index');
        sleep(6);                
        $client->takeScreenshot('screenshot_dashboard_index.png');
        $client->waitFor('#main-menu-sidebar-wrapper .settings');
```

How it looks on screenshot? Is page loaded? Is this element `'#main-menu-sidebar-wrapper .settings'` present?

**Comment by adityarai** [comment]
yes, the page is loading and successfully logged in to dashboard. After that, it cannot find the element 
'#main-menu-sidebar-wrapper .settings which does exists actually.

I tried your above code:
var_dump($subcrawler->html());

which is giving error:
Error is : InvalidArgumentException: The current node list is empty.

**Comment by domis86** [comment]
ok, lets see - please try like this:

```
var_dump( $client->getCrawler()->filter('body')->html() );
```

Do you see in this html code the element with `id="main-menu-sidebar-wrapper"` ? And inside it element with class `settings` ? Can you paste this whole fragment here?

**Comment by adityarai** [comment]
``PANTHER_NO_HEADLESS=1 bin/phpunit
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Testing Project Test Suite
E                                                                   1 / 1 (100%)string(21711) "<body class="user"><div class="header-wrapper content-header-first flex-box space-between"><div><div class="flex-box space-between"><div class="logo margin-right50"></div></div></div><div class="hide-1198">
                                    Registered Devices&nbsp;(0)&nbsp;&nbsp;|&nbsp;
                    <span class="">
                        Available Updates&nbsp;(<span class="availableUpdates">4250</span>)</span></div><div class="relative-layout"><div class="flex-box flex-end align-item-center"><a data-id="voucher" data-path="/claim/voucher/form" class="button bg-white-green hide-598 margin-right12">Claim Voucher</a><a data-id="package" data-path="/buy/update/package" class="button bg-white-green hide-598">Buy New Updates</a><div class="hide-598"><div class="relative-layout locale-wrapper"><a class="locale-bttn color-white margin-left22 en">English</a><ul class="drop-down-menu locale-drop-down hidden"><li><a class="en" rel="alternate" data-lang="en" hreflang="en" href="http://127.0.0.1:9080/dashboard/index">English</a></li><li><a class="de" rel="alternate" data-lang="de" hreflang="de" href="http://127.0.0.1:9080/de/dashboard/index">German</a></li></ul></div></div><img class="margin-left22 hide-598 height30 width30 border50" src="/uploads/user/yoqej5e720fe3e1c44.jpeg"><div class="relative-layout flex-box space-between"><a href="javascript:;" class="margin-left12 drop-down-menu-button color-white nowrap hide-1350">
                                                            admin
                                                        <span class="margin-left5 arrow-down-white"></span></a><a href="javascript:;" class="drop-down-menu-button margin-left22 hidden dpl-1350"><span class="menu-bar"></span></a><div id="dash-setting-drop-down" class="drop-down-menu hidden br-4"><ul class="hide-769 default-dropdown"><li class="user-details"><h4>admin</h4></li><li><a href="/sandbox/index">Start sandbox mode</a></li><li><a href="/user/edit-profile">Personal Settings</a></li><li><a href="/logout">Logout</a></li><li class="hidden show-1198">Registered Devices&nbsp;(0)&nbsp;&nbsp;|&nbsp;
                                    <span class="">
                        Available Updates&nbsp;(<span class="availableUpdates">4250</span>)</span></li></ul><div class="hidden show-769"><div class="flex-box space-between margin-aside"><h6 class="semi-bold">MENU</h6><div class="hidden show-598 "><div class="relative-layout locale-wrapper"><a class="locale-bttn  margin-left22 en">English</a><ul class="drop-down-menu locale-drop-down hidden"><li><a class="en" rel="alternate" data-lang="en" hreflang="en" href="http://127.0.0.1:9080/dashboard/index">English</a></li><li><a class="de" rel="alternate" data-lang="de" hreflang="de" href="http://127.0.0.1:9080/de/dashboard/index">German</a></li></ul></div></div></div><div class="margin-aside">
                                Registered Devices&nbsp;(0)&nbsp;&nbsp;|&nbsp;
                                <span class="">
                        Available Updates&nbsp;(<span class="availableUpdates">4250</span>)</span></div><div class="hidden show-598 margin-aside"><a data-id="package" data-path="/buy/update/package" class="button wid100 semi-bold width100 bg-green">Buy New Updates</a><a data-id="voucher" data-path="/claim/voucher/form" class="button wid100 semi-bold width100 bg-green margin-top12">Claim Voucher</a></div><div id="main-menu-wrapper"><ul class="main-menu"><li><a class="home active" href="/dashboard/index">Home</a></li><li class=""><a class="expand devices " href="/device/list">Devices</a><ul class="inner-menu devices-menu"><li><a class="" href="/device/list">Just Registered</a></li><li><a class="" href="/device/blacklist">Blacklisted</a></li><li><a class="" href="/device/groups">Devicegroups</a></li></ul></li><li class=""><a class="expand rollouts " href="/rollout/list">Rollouts</a><ul class="inner-menu rollouts-menu"><li><a class="" href="/rollout/list/planned">Planned</a></li><li><a class="" href="/rollout/list/running">Running</a></li></ul></li><li class=""><a class=" filegroups" href="/filegroup/">Filegroups</a></li><li class=""><a class="wishlist " href="/wishlist/">Wishlist</a></li><li class=""><a class="support " href="/support/">Support</a></li><li><a class="filegroups " href="/frontend/order/list">Orders</a></li><li class=""><a class="users expand " href="/user/list">Users</a><ul class="inner-menu"><li><a class="" href="/user-group/list">Usergroups</a></li></ul></li><li><a class="settings " href="/dashboard/settings">Settings</a></li></ul></div></div></div></div></div></div></div><div class="main-menu-sidebar-wrapper hide-769"><h6 class="margin30 semi-bold">MENU</h6><div id="main-menu-wrapper"><ul class="main-menu"><li><a class="home active" href="/dashboard/index">Home</a></li><li class=""><a class="expand devices " href="/device/list">Devices</a><ul class="inner-menu devices-menu"><li><a class="" href="/device/list">Just Registered</a></li><li><a class="" href="/device/blacklist">Blacklisted</a></li><li><a class="" href="/device/groups">Devicegroups</a></li></ul></li><li class=""><a class="expand rollouts " href="/rollout/list">Rollouts</a><ul class="inner-menu rollouts-menu"><li><a class="" href="/rollout/list/planned">Planned</a></li><li><a class="" href="/rollout/list/running">Running</a></li></ul></li><li class=""><a class=" filegroups" href="/filegroup/">Filegroups</a></li><li class=""><a class="wishlist " href="/wishlist/">Wishlist</a></li><li class=""><a class="support " href="/support/">Support</a></li><li><a class="filegroups " href="/frontend/order/list">Orders</a></li><li class=""><a class="users expand " href="/user/list">Users</a><ul class="inner-menu"><li><a class="" href="/user-group/list">Usergroups</a></li></ul></li><li><a class="settings " href="/dashboard/settings">Settings</a></li></ul></div></div><div class="content-wrapper"><div class="errorMsg"></div><input type="hidden" name="user_page_limit" id="user_page_limit" value="75"><div><h3 class="flex-box space-between margin-top20 bottom15 mob-display-block">Dashboard
    </h3><div><div style="display: flex;"><div class="pad20 bg-white box-shadow-1 radius3 bottom5 margin-right5" style="flex: 2.1;"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><div class="chart-title-wrapper"><div class="flex-row float-left">Usage</div><div class="flex-row float-right usage-legend-wrapper"><ul><li class="li-green"><span>-</span> Number of Devices (0)</li><li class="li-orange"><span>-</span> Number of Files (0)</li><li class="li-yellow"><span>-</span> Number of updates done (0)</li></ul></div><div class="clearfix"></div></div><canvas id="char1" width="654" height="327" style="display: block; width: 654px; height: 327px;" class="chartjs-render-monitor"></canvas></div><div class="pad20 bg-white box-shadow-1 radius3 bottom5" style="flex: 1;"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><div class="chart-title-wrapper">Security level</div><canvas id="char2" width="312" height="156" class="chartjs-render-monitor" style="display: block; width: 312px; height: 156px;"></canvas><div class="security-level-list"><ul><li class="li-green"><span>-</span> 90% of all devices are secured by the latest version update</li><li class="li-yellow"><span>-</span> Only 50% of all devices are secured by the latest version update</li><li class="li-orange"><span>-</span> 90% of all devices are secured by the latest version update file, but the last update file is more than 6 months old</li><li class="li-red"><span>-</span> Less than 50% of all devices are secured by the latest version update</li></ul></div></div></div><div style="display: flex"><div class="pad20 bg-white box-shadow-1 radius3 bottom5 margin-right5" style="flex: 1;"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><div class="chart-title-wrapper">Number of Rollouts</div><canvas id="char3" width="307" height="153" class="chartjs-render-monitor" style="display: block; width: 307px; height: 153px;"></canvas></div><div class="pad20 bg-white box-shadow-1 radius3 bottom5" style="flex: 1"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><div class="chart-title-wrapper">Update Processes</div><canvas id="char4" width="307" height="153" class="chartjs-render-monitor" style="display: block; width: 307px; height: 153px;"></canvas></div><div class="pad20 bg-white box-shadow-1 radius3 bottom5 margin-left5" style="flex: 1"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div><div class="chart-title-wrapper">Number of Devices</div><canvas id="char5" width="307" height="153" class="chartjs-render-monitor" style="display: block; width: 307px; height: 153px;"></canvas></div></div></div><script>
        usageChart(document.getElementById('char1').getContext('2d'));
        securityLevel(document.getElementById('char2').getContext('2d'), 'pie');
        numberOfRollouts(document.getElementById('char3').getContext('2d'));
        updateProcesses(document.getElementById('char4').getContext('2d'), 'pie');
        numberOfDevices(document.getElementById('char5').getContext('2d'));

        var securityLevelElement = null;
        var numberOfDevicesElement = null
        var numberOfRolloutsElement = null;
        var updateProcessesElement = null;
        var usageChartElement = null;

        function securityLevel(ctx) {
            function drawNeedle(radius, radianAngle) {
                var canvas = document.getElementById("char2");
                var ctx = canvas.getContext('2d');
                var cw = canvas.offsetWidth;
                var ch = canvas.offsetHeight + 30;
                var cx = cw / 2;
                var cy = ch - (ch / 4);

                ctx.translate(cx, cy);
                ctx.rotate(radianAngle);
                ctx.beginPath();
                ctx.moveTo(0, -7);
                ctx.lineTo(radius, 0);
                ctx.lineTo(0, 7);
                ctx.fillStyle = 'rgba(0, 0, 0, 0.8)';
                ctx.fill();
                ctx.rotate(-radianAngle);
                ctx.translate(-cx, -cy);
                ctx.beginPath();
                ctx.arc(cx, cy, 7, 0, Math.PI * 2);
                ctx.fill();
            }

            securityLevelElement = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    datasets: [{
                        data: [25, 25, 25, 25],
                        backgroundColor: [
                            '#d93a08',
                            '#f0952e',
                            '#f5d04d',
                            '#89b70f'
                        ],
                        borderColor: [
                            '#d93a08',
                            '#f0952e',
                            '#f5d04d',
                            '#89b70f'
                        ],
                        borderWidth: 0,
                        hoverBorderWidth: 0
                    }]
                },
                options: {
                    events: [],
                    animation: {
                        onComplete: function () {
                            drawNeedle(50, ( 180 + ( 80 * 1.8 ) ) * Math.PI / 180);
                        }
                    },
                    rotation: 1 * Math.PI,
                    circumference: 1 * Math.PI,
                    legend: {
                        display: false
                    },
                    tooltips: {
                        enabled: false
                    },
                    showTooltips: false,
                    cutoutPercentage: 60,
                    responsive: true,
                    maintainAspectRatio: true,
                    plugins: {
                        labels: {
                            render: function (args) {
                                switch (args.index) {
                                    case 0: return '10%';
                                    case 1: return '40%';
                                    case 2: return '80%';
                                    case 3: return '100%'
                                }
                            },
                            fontColor: [
                                '#d93a08',
                                '#f0952e',
                                '#f5d04d',
                                '#89b70f'
                            ],
                            position: 'outside',
                            outsidePadding: 5,
                            textMargin: 5
                        }
                    }
                }
            });

        }

        function numberOfDevices(ctx) {
            var max = (0 > 0 ? 0 : 0);
            numberOfDevicesElement = new Chart(ctx, {
                type: 'bar',
                options: {
                    legend: {
                        position: 'right',
                        align: 'top'
                    },
                    responsive: true,
                    maintainAspectRatio: true,
                    plugins: {
                        labels: {
                            render: 'value',
                            fontColor: [
                                'rgba(128, 166, 66, 1)',
                                'rgba(240, 145, 38, 1)',
                            ],
                            position: 'outside',
                            outsidePadding: 5,
                            textMargin: 5
                        }
                    },

                    scales: {
                        yAxes: [{
                            display: false,
                            gridLines: {
                                display: false
                            },
                            ticks: {
                                max: max + 1,
                                display: false,
                                beginAtZero: true
                            }
                        }],
                        xAxes: [{
                            gridLines: {
                                display: false
                            },
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                },
                data: {
                    datasets: [{
                        label: 'In group',
                        data: [0],
                        backgroundColor: [
                            'rgba(128, 166, 66, 1)',
                        ],
                        borderColor: [
                            'rgba(128, 166, 66, 1)',
                        ],
                        borderWidth: 1
                    }, {
                        label: 'Not grouped',
                        data: [0],
                        backgroundColor: [
                            'rgba(240, 145, 38, 1)',
                        ],
                        borderColor: [
                            'rgba(240, 145, 38, 1)',
                        ],
                        borderWidth: 1
                    }]
                },

            });
        }

        function updateProcesses(ctx) {
            numberOfRolloutsElement = new Chart(ctx, {
                type: 'pie',
                options: {
                    legend: {
                        position: 'right',
                        align: 'top'
                    },
                    responsive: true,
                    maintainAspectRatio: true,
                    plugins: {
                        labels: {
                            render: 'value',
                            fontColor: [
                                'rgba(128, 166, 66, 1)',
                                'rgba(240, 145, 38, 1)',
                            ],
                            position: 'outside',
                            outsidePadding: 5,
                            textMargin: 5
                        }
                    }
                },
                data: {
                    labels: ['Running', 'Planned'],
                    datasets: [{
                        data: [20, 15],
                        backgroundColor: [
                            'rgba(128, 166, 66, 1)',
                            'rgba(240, 145, 38, 1)',
                        ],
                        borderColor: [
                            'rgba(128, 166, 66, 1)',
                            'rgba(240, 145, 38, 1)',
                        ],
                        borderWidth: 1
                    }]
                },

            });
        }

        function numberOfRollouts(ctx) {
            numberOfRolloutsElement = new Chart(ctx, {
                type: 'pie',
                options: {
                    legend: {
                        position: 'right',
                        align: 'top'
                    },
                    responsive: true,
                    maintainAspectRatio: true,
                    plugins: {
                        labels: {
                            render: 'value',
                            fontColor: [
                                'rgba(128, 166, 66, 1)',
                                'rgba(243, 200, 67, 1)',
                                'rgba(240, 145, 38, 1)'
                            ],
                            position: 'outside',
                            outsidePadding: 5,
                            textMargin: 5
                        }
                    }
                },
                data: {
                    labels: ['Running', 'Planned', 'Finished'],
                    datasets: [{
                        data: [parseInt(0), parseInt(0), parseInt(0)],
                        backgroundColor: [
                            'rgba(128, 166, 66, 1)',
                            'rgba(243, 200, 67, 1)',
                            'rgba(240, 145, 38, 1)',
                        ],
                        borderColor: [
                            'rgba(128, 166, 66, 1)',
                            'rgba(243, 200, 67, 1)',
                            'rgba(240, 145, 38, 1)',
                        ],
                        borderWidth: 1
                    }]
                },
            });
        }

        function usageChart(ctx) {
            usageChartElement = new Chart(ctx, {
                type: 'line',
                options: {
                    legend: {
                        display: false,
                    },
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                            },
                            gridLines: {
                                display: true
                            }
                        }],
                        xAxes: [{
                            gridLines: {
                                display: false
                            }
                        }]
                    },
                },

                data: {
                    labels: [''],
                    datasets: [
                        {
                            label: 'Number of Devices',
                            data: [],
                            type: 'line',
                            backgroundColor: [
                                'transparent',
                            ],
                            borderColor: [
                                'rgba(240, 149, 46, 1)',
                            ],
                        },
                        {
                            label: 'Number of Files',
                            data: [],
                            type: 'line',
                            backgroundColor: [
                                'transparent',
                            ],
                            borderColor: [
                                'rgba(245, 208, 77, 1)',
                            ],
                        },
                        {
                            label: 'Number of updates done',
                            data: [],
                            type: 'line',
                            backgroundColor: [
                                'transparent',
                            ],
                            borderColor: [
                                'rgba(149, 190, 48, 1)',
                            ],
                        },
                    ]
                },

            });
        }
    </script></div></div><div class="dash-setting-dd-wrapper"></div><div class="modal fade" id="asvin-popup-modal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button><div class="modal-main-content" id="showDiv"></div></div></div></div><iframe name="AjaxDownloaderIFrame" style="display: none;"></iframe></body>"


Time: 43.8 seconds, Memory: 20.00 MB

There was 1 error:

1) App\Tests\Controller\SecurityControllerTest::testLoginForm
Facebook\WebDriver\Exception\TimeoutException: 

/var/www/html/asvin-frontend/vendor/php-webdriver/webdriver/lib/WebDriverWait.php:71
/var/www/html/asvin-frontend/vendor/symfony/panther/src/Client.php:329
/var/www/html/asvin-frontend/tests/Controller/SecurityControllerTest.php:26
``

**Comment by domis86** [comment]
```
Yes, I printed the html code and .main-menu-sidebar-wrapper .settings exists.
```
Ok, can you paste html code here? The fragment which contains elements with class `main-menu-sidebar-wrapper` and inside of that it contains element with class `settings` and which inside contains `Settings` text?

Or please paste output of the following:

```
var_dump( $client->getCrawler()->filter('.main-menu-sidebar-wrapper')->html() );
```

**Comment by adityarai** [comment]
`string(1334) "<div class="main-menu-sidebar-wrapper hide-769"><h6 class="margin30 semi-bold">MENU</h6><div id="main-menu-wrapper"><ul class="main-menu"><li><a class="home active" href="/de/dashboard/index">Home</a></li><li class=""><a class="expand devices " href="/de/device/list">Geräte</a><ul class="inner-menu devices-menu"><li><a class="" href="/de/device/list">Gerade registriert</a></li><li><a class="" href="/de/device/blacklist">Blacklisted</a></li><li><a class="" href="/de/device/groups">Gerätegruppen</a></li></ul></li><li class=""><a class="expand rollouts " href="/de/rollout/list">Rollouts</a><ul class="inner-menu rollouts-menu"><li><a class="" href="/de/rollout/list/planned">Geplant</a></li><li><a class="" href="/de/rollout/list/running">Laufen</a></li></ul></li><li class=""><a class=" filegroups" href="/de/filegroup/">Dateigruppen</a></li><li class=""><a class="wishlist " href="/de/wishlist/">Wunschliste</a></li><li class=""><a class="support " href="/de/support/">Support</a></li><li><a class="filegroups " href="/de/frontend/order/list">Aufträge</a></li><li class=""><a class="users expand " href="/de/user/list">Benutzer</a><ul class="inner-menu"><li><a class="" href="/de/user-group/list">Benutzergruppen</a></li></ul></li><li><a class="settings " href="/de/dashboard/settings">Einstellungen</a></li></ul></div></div>"`

**Comment by domis86** [comment]
Maybe on whole page there is several elements with class `settings`? Try `->first()` after `filter`:
```
 $linkCrawler = $client->getCrawler()->filter('.settings')->first()->link();
 $client->click($linkCrawler);
```

Also, are you sure that this element `<a class="settings " href="/de/dashboard/settings">Einstellungen</a>`  is visible?

**Comment by adityarai** [comment]
OK, I got it. The issue was the sidebar menu as well as dropdown is hidden in responsive view (Mobile view) because panther opens up the browser as small resized frame and inspector opened by default. Please see the image attached for the same. 
So it is working when I use the command execute script to open the menu and clicking the link works for me.
```
        client->executeScript("$('#dash-setting-drop-down').toggle()");
        $linkCrawler = $client->getCrawler()->filter('#dash-setting-drop-down .settings')->link();
        $client->click($linkCrawler);
```

So, is there a way to customized panther configuration to open a browser in maximized window and inspector closed
![Screenshot from 2020-05-14 20-23-00](https://user-images.githubusercontent.com/1521692/81950713-f3682f80-9621-11ea-80bf-4cb4c7485b1f.png)
![Screenshot from 2020-05-14 20-22-36](https://user-images.githubusercontent.com/1521692/81950721-f531f300-9621-11ea-9d55-33e4c28f6e15.png)
![Screenshot from 2020-05-14 20-22-10](https://user-images.githubusercontent.com/1521692/81950725-f6632000-9621-11ea-84e9-bc5a7709b539.png)


.
