### ISSUE TITLE
Add support to access the browser's console

### ISSUE THREAD

**Issue by dkarlovi** [symfony/panther#339]
If you're running Chrome inside a container, it's hard to view its Devtools (haven't found a way yet).

What would be better is to give the developer access to the console log, being able to directly inspect the errors (and later even assert against them).

See
https://github.com/php-webdriver/php-webdriver/issues/570#issuecomment-438640578

**Comment by huraji** [comment]
Have you found a workaround? It'd be so great to have it.

**Comment by dunglas** [comment]
I just needed to do this, and it's already possible. Here is how:

```php
namespace App\Tests;

use Symfony\Component\Panther\PantherTestCase;

class ConsoleTest extends PantherTestCase
{
    public function testConsole(): void
    {
        ($client = self::createPantherClient(
            [],
            [],
            [
                'capabilities' => [
                    'goog:loggingPrefs' => ['browser' => 'ALL'],
                ]
            ]
        ))->request('GET', '/');

        $logs = $client->getWebDriver()->manage()->getLog('browser');
    }
}
```

Maybe should we document this? Maybe should we always collect console logs in test mode? Maybe should we add a higher level API? But at least it's doable.

**Comment by dkarlovi** [comment]
@dunglas IMO, a higher level API would be a better choice since it allows for asserting against the logs.

**Comment by huraji** [comment]
I agree with @dkarlovi as nice-to-have, but I believe also that the solution of @dunglas works already great.
Thanks.

**Comment by qozle** [comment]
Where does @dunglas 's code go for that?  I've been banging my head trying to get the console info all day.  I tried: 
```
$desiredCapabilities->setCapability('loggingPrefs', ['browser'=>'ALL']);
...
$logs = $driver->manage()->getLog('browser');
var_dump($logs);
```
but am just getting an empty array back.  I'm executing a bunch of JS asynchronously with:
```
$jsFile = fopen('grader.js', 'r');
$js = fread($jsFile, filesize('grader.js'));
fclose($jsFile);

$emailStats = $driver->executeAsyncScript($js);
```
which definitely does a number of `console.log()`s.  Would the `executeAsyncScript` be why I'm not getting any logs back?
