### ISSUE TITLE
Running all test cases error 

### ISSUE THREAD

**Issue by adityarai** [symfony/panther#344]
I have total of 45 test cases using default PantherClient. When I run all test cases, it throws http post error somewhere after the 12 test cases are over. But when I run it individually, it is working fine. I think the port is occupied and throwing error for all other test cases.
............EEEEEEEEEEEEEEEEEEEEE

Error For the first test case.
1) App\Tests\Controller\BackEndLoginDeviceViewControllerTest::testBackEndGoodCredentialLoginTabletView
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session/51cdf38e67c801d383875e3fe89324c6/element/0b3fc754-5e3d-41d9-98cb-6204db437875/click

**Comment by domis86** [comment]
It seems like after some test some resources are not cleaned up / tear down. When some test is leaving something after its execution (for example: data in db) then it may affect execution of some test later in suite.

Can you try finding out which test from those first 12 is causing this? I propose to: 

1. Add `$this->markTestSkipped();` to all first 12 tests.
2. Try to remove the skip on each of skipped tests one by one and run the test suite each time. 

This way you should find the test which causes 13th one to fail. Then look inside this test and try to locate any possible not cleaned resources et.

**Comment by adityarai** [comment]
I tried your way. Skipped all first 12 test cases and removed and tested one by one, its working fine without any issue for all the cases. By the way, I'm also using alice's ReloadDatabaseTrait to purge mysql database.

**Comment by domis86** [comment]
Ok. So what we know so far:
1. Running all tests causes 13th test to fail.
2. Running 12 first test skipped except 1 (each) makes all tests pass.

You should try to exclude other combinations - for example:.
1. Skip first 6.
2. Skip tests 7-12.
3. Skip one by one test from 1 to 12.

What is the effect of such combinations?

**Comment by adityarai** [comment]
Yes, I tried your approach and it works fine. Does it have to do anything with session because I'm storing the session data in database.

**Comment by domis86** [comment]
> Does it have to do anything with session because I'm storing the session data in database.

is possible - can you try clearing your session db table after each test (in `tearDown` method etc) ? It could be done via simple `TRUNCATE` or `DELETE` query probably

**Comment by adityarai** [comment]
@domis86 .. thanks for helping me out.. Its a system memory issue. I solved it by using this.

`PANTHER_NO_HEADLESS=1 php bin/phpunit --default-time-limit=240 --stderr --process-isolation`
