### ISSUE TITLE
Install chromedriver matching installed chrome version

### ISSUE THREAD

**Issue by dbrekelmans** [symfony/panther#356]
Currently `chromedriver-bin/update.sh` downloads and installs the latest chromedriver.
This will cause issues in CI if you are using a built image with an older chrome version.

Instead of installing the latest version, I suggest checking the installed chrome version and downloading the matching chromedriver.

You can get the matching version like this:

```
chrome_version=$(google-chrome --version | grep -ioE "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+")
driver_version=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chrome_version)
```

I didn't create a PR yet, because I'm unsure if getting the latest chromedriver version is a wanted feature.
Perhaps there could be 2 separate scripts or we could pass a --latest argument.

Let me know!

**Comment by dunglas** [comment]
Maybe should we :

* remove the ChrimeDriver and GeckoDriver form this repository
* rewrite the shell scripts as Symfony commands (so they will work on all platforms, including Windows and BSD)
* Ask the use to run this installation command before the first run if it doesn't have ChromeDriver/GeckoDriver installed locally.

To avoir compatibility issues, we should download the exact version of ChromeDriver corresponding with the local version of Chrome (some CIs and distributions ship old versions of Chrome requiring old versions of ChromeDriver).

WDYT?

**Comment by dbrekelmans** [comment]
Sounds good to me. I'll start on a draft.

**Comment by Kolvin** [comment]
This would help with building docker environments too as seen [here](https://github.com/symfony/panther/issues/304#issuecomment-676055116)

**Comment by dbrekelmans** [comment]
Update on the progress:

I'm working on supporting multiple OSes, browsers and drivers.

I extracted this to a separate package to better deal with the size, dependencies and testing (CI).

I will continue working on this and open a PR to use this package in panther when I have a first release ready.

**Comment by dbrekelmans** [comment]
For the folks watching this thread:

If you want to help work on the solution, there are a few [easy-to-do issues](https://github.com/dbrekelmans/browser-driver-installer/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) before I can make a release. Comment on one of the issues if you want to help out 😃
