### ISSUE TITLE
Unsupported version of Chrome

### ISSUE THREAD

**Issue by spolischook** [symfony/panther#387]
I have latest update on my Ubuntu 20.04.1 LTS with latest update of Chrome that is now version 87.

```
google-chrome-stable --version
Google Chrome 87.0.4280.66
```

I've got exception with most recent version of Panther dev-main

```
In WebDriverException.php line 125:
                                                                                     
  [Facebook\WebDriver\Exception\SessionNotCreatedException]                          
  session not created: This version of ChromeDriver only supports Chrome version 85
```

**Comment by spolischook** [comment]
@dunglas should I create this issue somewhere else?

**Comment by spolischook** [comment]
Temporary fix for Ubuntu - download 85 version of Chrome 
https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_85.0.4183.121-1_amd64.deb

**Comment by dbrekelmans** [comment]
Install `composer require --dev dbrekelmans/bdi` and run `vendor/bin/bdi` to install a compatible driver for your chrome version. Use the ENV var `PANTHER_CHROME_DRIVER_BINARY` to direct to the newly installed driver

**Comment by back-2-95** [comment]
I have this with Github Actions using the 0.8.0 version. Tests started to fail by themselves. Is this because ubuntu-latest has chrome 87 ?

I tried to overcome this with using `dbrekelmans/bdi` and setting `PANTHER_CHROME_DRIVER_BINARY` but no luck.
It gives this error:

```
RuntimeException: Could not start chrome. Exit code: 127 (Command not found). Error output: sh: 1: exec: /home/runner/work/MY-PROJECT/chromedriver: not found
```

bdi has downloaded the binary to `/home/runner/work/MY-PROJECT/chromedriver` so not found might come from there.

**Comment by dbrekelmans** [comment]
Only reason I can think of, is that `/home/runner/work/MY-PROJECT/chromedriver` is not accessible by panther (due to directory permissions).

BDI sets correct permissions on the driver itself, but doesn't modify the directory permissions
