### ISSUE TITLE
DomCrawler/Crawler.php throws "Required Param after Optional" Error in PHP8

### ISSUE THREAD

**Issue by hawkinbj** [symfony/panther#393]
Immediately crashes because Crawler.php constructor looks like this:
![Screen Shot 2020-12-09 at 3 08 48 PM](https://user-images.githubusercontent.com/952976/101695064-49bf1480-3a31-11eb-8aab-6b04078f45c6.png)

While the param $elements is typed, it's default value is [], which causes the error to be thrown. If it were null, no problem. 

More info here: https://php.watch/versions/8.0/deprecate-required-param-after-optional

**Comment by nicolas-grekas** [comment]
Can you please send a PR?

**Comment by hawkinbj** [comment]
https://github.com/hawkinbj/panther/tree/FIX-%23393
