### ISSUE TITLE
Testing screenshots

### ISSUE THREAD

**Issue by huraji** [symfony/panther#401]
Is there a way or a bundle (I'm thinking something like for image processing) to test screenshots taken with panther?

Thanks in advance.

**Comment by halfer** [comment]
This is rather too broad a question for a bugs/issue list, and is way outside of the scope of Panther. I would recommend [searching for this](https://duckduckgo.com/?q=test+screenshots+for+differences&ia=web), which leads to results [like this](https://sqa.stackexchange.com/questions/2459/compare-screenshots-of-rendered-web-pages).

**Comment by nusje2000** [comment]
@huraji does this issue require any more work, or can this issue be closed?

**Comment by huraji** [comment]
We can close it
