### ISSUE TITLE
Crawler can't find elements added after initial load

### ISSUE THREAD

**Issue by TomWhitson** [symfony/panther#405]
I've got the below script, the webpage loads then pops up a cookie consent form. The text on the button is "Agree".

I can see the pop up on screen but the waitForVisibility always times out. Is there anything required on the craweler to pick up dynamic content loaded via a script?

$_SERVER['PANTHER_NO_HEADLESS'] = 'TRUE';
$client = Client::createChromeClient();
$url = 'https://sky.com/myaccount/bb-and-talk';
$client->request('GET', $url);
$crawler = $client->getCrawler();

$client->waitForVisibility('button[title="Agree"]');
$button = $crawler->selectButton('Agree');
$button->click();

**Comment by nusje2000** [comment]
@TomWhitson the crawler is only a snapshot of the DOM it was created from. You have to reload the crawler by running `$crawler = $client->refreshCrawler()`.
