### ISSUE TITLE
Failed to connect to 127.0.0.1 port 9515: Connection refused

### ISSUE THREAD

**Issue by flim** [symfony/panther#410]
Im using panther in a symfony project.
Im not sure its panther issue, but can't find a fix so I post it here.

I use Panther to retrieve data form an external website.
It works well, but sometime i got this error and it failed. but I just have to run the script again and it works.
But other time its persisting and I cant use it for a moment. I dont know what's wrong and how to debug.

Need some clue to help me fix. Thank you

symfony 5.2.1
symfony/panther v0.9.0

I instantiate panther like this :
```php
 $this->client = Client::createChromeClient(null, [
    '--headless',
    '--no-sandbox',
    sprintf('--user-data-dir=%s', $pantherChromeUserDataDir)
]);
```

All informations I have is :
```bash
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http DELETE to /session/975206305b3956e15ddf874bb650edb1

Failed to connect to 127.0.0.1 port 9515: Connection refused in /home/flim/project/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:332
Stack trace:
#0 /home/flim/project/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(612): Facebook\WebDriver\Remote\HttpCommandExecutor->execute()
#1 /home/flim/project/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php(337): Facebook\WebDriver\Remote\RemoteWebDriver->execute()
#2 /home/flim/project/vendor/symfony/panther/src/Client.php(489): Facebook\WebDriver\Remote\RemoteWebDriver->quit()
#3 /home/flim/project/vendor/symfony/panther/src/Client.php(90): Symfony\Component\Panther\Client->quit()
#4 [internal function]: Symfony\Component\Panther\Clie in /home/flim/project/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php on line 332
```

**Comment by dunglas** [comment]
It looks like Chromedriver isn't started properly. Try to use `ps` to check if the `chromedriver` process is started. If it is, try to access it directly using `curl`.

**Comment by flim** [comment]
Thanks for your help.
Since I updated my code, I can't reproduce it anymore at the moment.
