### ISSUE TITLE
Adjust the size of the window/screenshot

### ISSUE THREAD

**Issue by OskarStark** [symfony/panther#428]
I tried sth like:
```php
<?php

declare(strict_types=1);

namespace App\Tests\Acceptance\Util;

use Facebook\WebDriver\WebDriverDimension;
use Symfony\Component\Panther\Client as PantherClient;
use Symfony\Component\Panther\PantherTestCase;

class ScreenshotTestCase extends PantherTestCase
{
    protected static function createPantherClient(array $options = [], array $kernelOptions = [], array $managerOptions = []): PantherClient
    {
        $client = self::createPantherClient();

        $size = new WebDriverDimension(1400, 4000);
        $client->manage()->window()->maximize()->setSize($size);

        return $client;
    }
}
```

But the size of the screenshot doesn't change 🤔

**Comment by marco-kretz** [comment]
Hey there,

had the same problem. Just add `--window-size=1400,900` as chrome arguments :)

**Comment by shadowc** [comment]
Hey, I'm facing the same issue! Could you give us a code example of where chrome arguments go, @marco-kretz ? Thanks!

**Comment by marco-kretz** [comment]
I'm just using env-vars for this. That's what I have in my .env:

`PANTHER_CHROME_ARGUMENTS="--disable-dev-shm-usage --window-size=1400,900 --no-sandbox --headless --hide-scrollbars"`

**Comment by shadowc** [comment]
Ahh, I see! Thank you! I'll try this!

**Comment by shadowc** [comment]
That TOTALLY works! May be in the future we can configure these arguments somewhere within the panther client creation (or a panther.xml.dist file or similar in our projects!)

**Comment by marco-kretz** [comment]
> That TOTALLY works! May be in the future we can configure these arguments somewhere within the panther client creation (or a panther.xml.dist file or similar in our projects!)

You can totally do that already :)

![image](https://user-images.githubusercontent.com/2982363/108548182-c13fd880-72eb-11eb-9c4d-4d0b9e2f800c.png)

**Comment by shadowc** [comment]
I see! May be this is not apparent from `createPantherClient`.

If I do:

```php
$this->client = static::createPantherClient(
    ['external_base_uri' => 'https://localhost:8000'],
    ['HTTPS' => true],
    ['capabilities' => [
        'acceptInsecureCerts' => true,
    ]],
);
```

Because I want to use an external server with https, then I need to figure out how this translates to the `createChromeClient` signature.

**Comment by shadowc** [comment]
From panther's source code:
```php
if (static::CHROME === $browser) {
            self::$pantherClients[0] = self::$pantherClient = Client::createChromeClient(null, null, $managerOptions, self::$baseUri);
        } else {
            self::$pantherClients[0] = self::$pantherClient = Client::createFirefoxClient(null, null, $managerOptions, self::$baseUri);
        }
```

May be we need to accept browser arguments from within `createPantherClient` to make it more accessible?

**Comment by shadowc** [comment]
It would appear by looking at the source code (if I'm not wrong) that if I call `Client::createChromeClient` I won't have started a WebServer (which I guess it's fine in my case, but not ALL cases) and I won't boot a kernel. What implications does this have for the test case?
