### ISSUE TITLE
Multiple Threads? 

### ISSUE THREAD

**Issue by christoph-werker** [symfony/panther#432]
Hello Together,

I am still a bit newer to test automation. Currently I have a Symfony Selenium setup and have been automating business processes with it. Unfortunately I can only run one process at a time.

Is it possible to run multiple processes at once with Panther? 

**Example:**

- Visit Wikipedia -> Search for Term....
- visit Google -> Search for Term...

When I try to do the same with my current setup, an instance is terminated as soon as a process is finished.

I would like to offer this for my clients and they would use the function at the same time.

Thanks.

**Comment by OskarStark** [comment]
Did you tried to create an additional client?
https://github.com/symfony/panther#creating-isolated-browsers-to-test-apps-using-mercure-or-websocket

**Comment by christoph-werker** [comment]
Thanks @OskarStark 
Does this also work for Chromedriver? And are all the functionalities included to easily navigate and perform actions such as login, file download (.pdf).

**Comment by nusje2000** [comment]
@christoph-werker the behaviour of the additional client is the same as the client created via `createPantherClient`. Panther supports multiple managers and the chromedriver is indeed one of them. Login can be easily done by using the Form component in panther. For more information about the use of panther you can checkout the documentation containing a lot of examples. Hope this helps :)

**Comment by christoph-werker** [comment]
thank you for your reply.

That means when i use `createPantherClient` with a free Post i am able to run parallel instances correct? I will definitely test this out.
```
$client = $this->createPantherClient([], [], [
    'port' => (int) (9515 + freePort()),
]);
```

Thanks i will close this.

**Comment by nusje2000** [comment]
@christoph-werker it is a requirement that you use `createAdditionalPantherClient` because `createPantherClient` will close the current client if one already exists, while `createAdditionalPantherClient` will always open a new one. But besides that, the example you provided should work.

**Comment by christoph-werker** [comment]
One last question. How do I monitor the server load? Not that all at once too many clients were created, so that the server crashes.

I once had the problem that too many ChromeDriver instances were open, so that the server went down.

**Comment by nusje2000** [comment]
@christoph-werker think the best solution is creating a runner that only allows x clients to run in parallel. But I don't know a solution for that problem of the top of my head.
