### ISSUE TITLE
How to add logging commands to ChromeDriver binary?

### ISSUE THREAD

**Issue by halfer** [symfony/panther#434]
Hi all. I am using these software components:

* symfony/panther 1.0.1
* phpunit/phpunit 9.5.2
* brianium/paratest v6.2.0
* PHP 7.4.11
* ChromeDriver 88.0.4324.96
* Google Chrome 88.0.4324.150

I have an interesting problem. I want to be able to add these parameters into the `chromedriver` call:

* --log-level
* --log-path
* --append-log

However I am prevented from doing so by this code:

```
/**
 * @author Kévin Dunglas <dunglas@gmail.com>
 */
final class ChromeManager implements BrowserManagerInterface
{
    use WebServerReadinessProbeTrait;

    private $process;
    private $arguments;
    private $options;

    /**
     * @throws \RuntimeException
     */
    public function __construct(?string $chromeDriverBinary = null, ?array $arguments = null, array $options = [])
    {
        $this->options = array_merge($this->getDefaultOptions(), $options);
        $this->process = new Process([$chromeDriverBinary ?: $this->findChromeDriverBinary(), '--port='.$this->options['port']], null, null, null, null);
        $this->arguments = $arguments ?? $this->getDefaultArguments();
    }

    ...
```

As you can see, the first parameter to the `Process` instantiation is thus:

```
[$chromeDriverBinary ?: $this->findChromeDriverBinary(), '--port='.$this->options['port']]
```

I would need to inject my additional parameters in here. However, `ChromeManager` has been declared as `final` and so I cannot create a child from it.

I have tried creating a fake `chromedriver` that adds new params and then calls the real one, but this results in orphaned `chromedriver` child processes. That might be fixable, but really it is a consequence of this lack of extensibility in the first place. Any ideas whether there is a clean way I can pass these params?

**Comment by halfer** [comment]
Aha, despite extensive searching prior to raising this, this appears to be an exact duplicate of #215, and there is a PR in flow!

**Comment by halfer** [comment]
@nusje2000 - I have quite a clean hack to use in the meantime. Use this as a custom `chromedriver` pointed to using a fully-qualified pathname in your project. It requires the real `chromedriver` to be available in your PATH:

```
#!/bin/bash
#
# Forces the ChromeDriver to do the logging we want - which does not seem to
# work via the normal Panther `createChromeClient` method.
#
# Change log-level here to any supported option: ALL, DEBUG, INFO, WARNING, SEVERE, OFF

# Here is the call to the real ChromeDriver. I have found that
# exec is necessary to bring the binary under the same PID, otherwise the new child process
# appears to become orphaned
exec chromedriver --log-level=INFO --log-path="${TEST_LOG_PATH}/chromedriver.log" --append-log "$@"
```

**Comment by nusje2000** [comment]
Thanks for the temporary solution, this is gonna be really helpful ♥️

**Comment by halfer** [comment]
No worries @nusje2000, it's taken me hours to get the `exec` thing - the script without this worked, but it was scattering orphaned processes all over the shop! Since I am using ParaTest, there were quite a lot of them, and it was resulting in port conflicts.
