### ISSUE TITLE
Release v1.0.2

### ISSUE THREAD

**Issue by lolautruche** [symfony/panther#445]
Could you please publish the `v1.0.2` release?
It would indeed contain the fix from #423, as currently the [Blackfire integration with Symfony functional tests](https://blackfire.io/docs/php/integrations/symfony/functional-tests) (which uses Panther) is broken because of the [`$client::createWebDriverByFromLocator($selector)` change](https://github.com/symfony/panther/commit/016d7ef7f088657db060fd70a72ea00e57f3a5b4#diff-5a36a8a6b4788c6b8a1f204aec71ec967c70b1a8a2b6eae4e0dc875f6b9fd0faR48)

Thanks in advance :pray:

**Comment by halfer** [comment]
You can just use a dependency of `dev:master` in the short term.

**Comment by lolautruche** [comment]
Hello @halfer 

I know I can override this, and I did. However, this affects anyone using the Blackfire SDK with Symfony functional tests.
It would be really nice if you could tag a new release :slightly_smiling_face:

**Comment by halfer** [comment]
Hi @lolautruche - I am not part of the core team, I can't do releases 😇

However I have just spotted there are two releases since this conversation - so the fix you need should be in the latest one.

**Comment by lolautruche** [comment]
Hey @halfer 
Yes indeed. I'm closing this issue now.
Thanks!
