### ISSUE TITLE
[v1.1.0] PANTHER_NO_HEADLESS adds --headless

### ISSUE THREAD

**Issue by metaer** [symfony/panther#486]
Bug in v1.1.0:
PANTHER_NO_HEADLESS adds --headless option
It behaves as PANTHER_HEADLESS (without "NO") would behave if it existed

```php
        if ($_SERVER['PANTHER_NO_HEADLESS'] ?? true) {
            $args[] = '--headless';
            $args[] = '--window-size=1200,1100';
            $args[] = '--disable-gpu';
        }
```

if I have PANTHER_NO_HEADLESS=1 in my .env.local I expected that --headless option will not be added. In v1.0.1 it works this way. But in v1.1.0 it works vice versa.

**Comment by metaer** [comment]
It seems correct condition is:

```php
if (!($_SERVER['PANTHER_NO_HEADLESS'] ?? false)) {
    $args[] = '--headless';
    $args[] = '--window-size=1200,1100';
    $args[] = '--disable-gpu';
}
```

Shoud I create PR ?

**Comment by dunglas** [comment]
Oops my bad. Yes please create a PR I'll tag a patch version ASAP.

**Comment by metaer** [comment]
PR: https://github.com/symfony/panther/pull/487

**Comment by dunglas** [comment]
Release tagged! Thanks @metaer
