### ISSUE TITLE
Missing execution bit from chromedriver preventing its execution

### ISSUE THREAD

**Issue by XavierVallot** [symfony/panther#54]
Hi,
I'm trying to use Panthère in Symfony on Debian, but I have this error when launching my tests :
`RuntimeException: sh: 1: exec: /srv/app/vendor/symfony/panthere/src/ProcessManager/../../chromedriver-bin/chromedriver_linux64: Permission denied`

Indeed, here's the permission status :
![image](https://user-images.githubusercontent.com/9256415/42582311-14c45cae-852f-11e8-9a44-6422190dbdbb.png)

Is there a way to install chromedriver without setting permissions by hand ?

**Comment by dunglas** [comment]
Is the project in a shared folder? The mount driver you use most likely don't preserve permissions.

**Comment by Kocal** [comment]
Hey, me and @XavierVallot are working together and I just encountered the same issue.
So yes, we are on a shared FS (Vagrant), but I think it's more a composer issue than something else.

When running composer:
![selection_779](https://user-images.githubusercontent.com/2103975/43848051-63d8db30-9b32-11e8-8024-d531c7c2abb7.png)

When manually cloning the repo:
![selection_780](https://user-images.githubusercontent.com/2103975/43848054-6649305e-9b32-11e8-93ab-3ef499aab59a.png)

Inside the VM, we are using php 7.2.7 and composer 1.6.5.

**Comment by Kocal** [comment]
Well...

I just ran composer outside the VM and everything is fine :thinking: 
![selection_782](https://user-images.githubusercontent.com/2103975/43848613-9f9c2dba-9b33-11e8-87ce-dd020e2bbbd8.png)

Outside the VM, I am using php 7.2.8 and composer 1.7.1.

I will try to update VM's composer to the same version, and see what happens.

**Comment by Kocal** [comment]
@dunglas you are right, this problem only happens when we require a dependency inside this shared folder. I tried with non-shared folder `/srv/app2` and it works.

I tried to update our Vagrantfile with this but it does not work:
```diff
config.vm.synced_folder '.', '/srv/app',
  type: 'nfs',
-  mount_options: ['nolock', 'actimeo=1', 'fsc']
+  mount_options: ['nolock', 'actimeo=1', 'fsc', 'exec']
```

Do you have an idea @tristanbes? :thinking:

**Comment by tristanbes** [comment]
maybe @nervo could enlight us on this (seems to happens only on Linux since on my OSX host, I can't reproduce)

**Comment by Kocal** [comment]
Maybe it is related to composer too?

**Comment by supertanuki** [comment]
@XavierVallot @Kocal @tristanbes did you fix the problem? same here with vagrant and shared FS

**Comment by tristanbes** [comment]
no, the team stopped using Panthere because of this issue. It was a nightmare to debug/work with. Other executables are fine (doctrine, symfony console etc...) it seems that it's related only with panthere.

We used Cypress for E2E tests.

**Comment by supertanuki** [comment]
thanks @tristanbes

**Comment by dunglas** [comment]
@tristanbes you can always use your own binary using `PANTHER_CHROME_DRIVER_BINARY` if there is no other choice.
If someone can provide a repository with a reproducer, I can try to debug this.

**Comment by tristanbes** [comment]
We tried that, but then other problem appeared. Maybe @kocal remembers what it was. But it would be best if it works out of the box 📦 without the need to provide our own binaries.


Envoyé de mon iPhone

**Comment by dunglas** [comment]
I agree, but as I never faced this problem (and it is likely due to NFS, a volume or something like that), it's hard to debug without reproducer.

**Comment by Kocal** [comment]
If I remember well, I think it was a composer issue at the final... :disappointed: 
This is what I faced:

| command | context | binary is executable ? | 
| ------- | ------- | ---------------------- |
| git clone | outside VM | yes |
| git clone | inside VM, in shared path (NFS) | yes |
| git clone | inside VM, in non-shared path | yes |
| composer req | outside VM | yes |
| composer req | inside VM, in shared path (NFS) | **no** |
| composer req | inside VM, in non-shared path | **no** |

![capture d ecran de 2018-10-08 22-15-02](https://user-images.githubusercontent.com/2103975/46631447-c00d1700-cb47-11e8-84ba-7eb0d000d459.png)

I made a reproduction repository here: https://github.com/Kocal/symfony-panther-missing-executable-bit-nfs

Thanks for your time!

**Comment by Kocal** [comment]
> and it is likely due to NFS, a volume or something like that

Yes, but not in this case.

I tried to install `doctrine/orm` because it's a package that has binary executables, and the file `vendor/doctrine/orm/bin/doctrine` is executable.

By looking at its `composer.json`, there is a special field `bin` which is specified, and I think it's the key because it's missing in Panther. 

What happens if you add `"bin": ["chromedriver-bin/chromedriver_linux64"]` in `composer.json`?

**Comment by dunglas** [comment]
Ok, I think I get what the problem is. As the Composer warning explain, `unzip` is not installed. Unfortunately, it looks like the php ZIP extension [is not able to preserve the executable bit of binaries](https://github.com/composer/composer/issues/7383).
Can you try if installing `unzip` fixes the problem? If it's the case, we should update the documentation to explain than having `unzip` installed is mandatory.

**Comment by dunglas** [comment]
@Kocal, it's probably just a side effect, the `bin` entry allows packages to expose command line tools (https://getcomposer.org/doc/articles/vendor-binaries.md).
Maybe composer re-add the `+x` bit when copying the script in this repository, but the underlying issue is more likely that `unzip` is missing.

I don't think that copying Chromedriver in `vendor/bin` is a good idea, as it's not a tool designed to be used directly by the end user.

**Comment by Kocal** [comment]
> As the Composer warning highlights, unzip is not installed. 

Good catch, that was the problem!

**Comment by dunglas** [comment]
Ok, I'm glad we sorted this out! The next step is to make it bold in the documentation that `unzip` must be installed to not have this issue.

**Comment by tristanbes** [comment]
Thanks guys ! Glad you have sorted this out 

Envoyé de mon iPhone

**Comment by mickaelandrieu** [comment]
Need to check this, this could unlock some important topics for me 👍

**Comment by supertanuki** [comment]
@dunglas thanks, installing `unzip` solved the problem for me too.

Then I had another problem:

> chromedriver_linux64: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

I installed libxi6 and libgconf-2-4 too to fix the problem.
Hope this will help someone.

**Comment by stof** [comment]
> Maybe composer re-add the `+x` bit when copying the script in this repository

yeah, composer indeed makes the file executable when creating it in `vendor/bin` (which makes the original file executable in case a symlink was used, which is the case on \*nix systems)

**Comment by dunglas** [comment]
@supertanuki: Chrome and Chromedriver binaries require some libraries that are not installed by default with Alpine.
Here it complains about the ones provided by Xorg, but there are probably some other missing.

**Comment by Surf-N-Code** [comment]
Sorry to comment an old issue, but I think it may be interesting for others landing here from google.

I kept getting this error:
`RuntimeException: Could not start chrome (or it crashed) after 30 seconds.`

Which was also due to the fact that I had run composer install before installing unzip.
