### ISSUE TITLE
renaming functions to make them easier to understand?

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panther#58]
Following on from [this pr](https://github.com/symfony/panther/pull/43) I'd like to suggest some naming alternatives which are perhaps a bit funky:

`takeScreenshot` -> `screenshot` (also, can a basedir be set for all screenshots, e.g. `var/screenshots`?
`sendKeys` -> `type` (as @javiereguiluz suggests)
`getLocation` -> ?
`getLocationOnScreenOnceScrolledIntoView()` -> ??

**Comment by dunglas** [comment]
I’m not in favor of aliasing or renaming native WebDriver methods: Facebook PHP WebDriver is close from the protocol. Using the same names than the ones defined in the protocol (a W3C standard) makes it easier to debug and to find examples coming from other ecosystems. All WebDriver related libraries use the same names (the ones defined in the spec) across languages, so when you are looking something specific you always find resources, at least written in Java or JS.
I think it’s a hug benefit and we should not change this.

**Comment by javiereguiluz** [comment]
Let's close this old issue because it didn't gain enough traction. We can always revisit it in the future. Thanks!
