### ISSUE TITLE
Do you plan to update panther product till Symfony 6.2?

### ISSUE THREAD

**Issue by Mepcuk** [symfony/panther#585]
Do you plan to update panther product till Symfony 6.2?

**Comment by dunglas** [comment]
Yes. We don't plan to deprecate Panther.

**Comment by wouterj** [comment]
I'm not sure what you mean. As far as I can see, this package supports Symfony 6.2.
If you find anything to not work, please share details about it (ideally a reproducer or a bugfix).

**Comment by arderyp** [comment]
I suspect OP may have simply been concerned by the fact that there hasn't been a release in over a year and there hasn't even been a commit to `main` in 4 months.  At least, that's the thought I had when I saw those numbers while contemplating [phpunit 10 compatibility](https://github.com/symfony/panther/issues/586)

**Comment by dunglas** [comment]
The library is pretty stable is doesn't require much work. However we indeed have work for PHPUnit 10 compatibility.

**Comment by arderyp** [comment]
That's fair enough.  I hope I didn't come off as judgemental, that's wasn't my intent.  I think it actually extremely commendable when packages become stable enough to not need frequent updates (and aren't endlessly chasing features that lead to a complexity spiral).  My reaction was just the knee jerk default these days when nearly every popular package is pushing updates with incredible frequency)

You all are doing great work, and it's an awesome package :)

**Comment by arderyp** [comment]
> The library is pretty stable is doesn't require much work. However we indeed have work for PHPUnit 10 compatibility.

@dunglas @wouterj while the package is stable, it does still need some regular maintenance. Can we please merge to PHPUnit 10 compatibility PR to keep it stable and up to date?

https://github.com/symfony/panther/pull/589#issuecomment-1502169549
