### ISSUE TITLE
is Symfony\Component\Panther\ServerExtension PHPUnit 10 compatible?

### ISSUE THREAD

**Issue by arderyp** [symfony/panther#586]
I know this package depends on `symfony/phpunit-bridge`, which is [not yet PHPUnit 10 compatible](https://github.com/symfony/symfony/issues/49069). But, once it is, will `Symfony\Component\Panther\ServerExtension` be ready?

**Comment by arderyp** [comment]
It appears to be still using the Hook-based extension system, which is deprecated.  Here is a great writeup about thew new Event system in phpunit 10 with examples for how to implement it: https://localheinz.com/articles/2023/02/14/extending-phpunit-with-its-new-event-system/

there are other deprecations that need to be addressed for 9-10-10 migration, but most of them are simple patterns that can be done easily with Rector's phpunit 10 migration (or manually). But the extension migration requires a decent amount of work/thinking/refactoring.

**Comment by wouterj** [comment]
> But, once it is, will Symfony\Component\Panther\ServerExtension be ready?

If someone contributes the necessary changes, I'm sure it will be :)

**Comment by arderyp** [comment]
the answer is no.

I opened a new issue for the task: https://github.com/symfony/panther/issues/588
