### ISSUE TITLE
Make Panther PHPUnit 10 compatible

### ISSUE THREAD

**Issue by arderyp** [symfony/panther#588]
Now that PHPUnit 10 is out, I'm adding this issue to the queue

**Comment by arderyp** [comment]
is no one is working on this, I may be able to dedicate some time to looking into it.

@dunglas, since PHPUnit 10 is a substantial refactor, I am not yet sure how feasible it would be for Panther to support, for example, both 9 and 10.  It looks like Panther isn't actually dependent directly on `phpunit/phpunit`, but rather `symfony/phpunit-bridge`, which is also not PHPUnit 10 compatible.

Do you think work on this issue should wait until after `phpunit-bridge` supports 10?

Do you intend to attempt to support multiple PHPUnit versions, or would this issue warrant a new major `3` release and dropped support for PHPUnit <10?

**Comment by arderyp** [comment]
it looks like `doctrine-test-bundle` does handle support for multiple php version, so maybe this is doable here as well: https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/PHPUnit/PHPUnitExtension.php

**Comment by Chris53897** [comment]
@arderyp Thanks for your hard work here. Maybe you can close this issue as completed?
