### ISSUE TITLE
should getCurrentUrl return the full url, or the relative url?

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panther#60]
It's a bit strange when making a `$client->request('GET', '/foos/')` for `$client->getCurrentURL()` to return the full url including the host. Shouldn't it just return the relative url?

e.g. getCurrentURL returns: `http://127.0.0.1:9000/foos/`, and I think it should return `/foos/`.

**Comment by dunglas** [comment]
We should copy the behavior of Goutte.

**Comment by ChangePlaces** [comment]
i think you should make a separate package that is `webdriverMangledToAllowMeToReuseMyGoutteCode` and not try to force this to be it.

**Comment by nicolas-grekas** [comment]
Closing as this matches the design principles as explained.
