### ISSUE TITLE
Problem with detect driver

### ISSUE THREAD

**Issue by pawel747** [symfony/panther#601]
Hi

I have a problem with detecting the driver using the command `vendor/bin/bdi detect drivers`

In the output I only see information about deprecated. I don't see the green bar that said Chromedriver and Browser detected correctly.

Chromedriver version: `115.0.5790.102`
Chrome version: `115.0.5790.114`

I see an error when running the tests: `Facebook\WebDriver\Exception\UnknownErrorException: unknown error: cannot find Chrome binary` 

Everything worked until the automatic update of the browser.

Please help.

**Comment by Florian-B** [comment]
I encountered the same problem. As a workaround I installed the previous version of Chromium.

It seems related to https://github.com/dbrekelmans/browser-driver-installer/issues/73

A PR is open https://github.com/dbrekelmans/browser-driver-installer/pull/75 but it doesn't seem to be progressing.

**Comment by jumaris88** [comment]
`$client = Client::createChromeClient("your_drivers_path/chromedriver.exe");`

**Comment by dunglas** [comment]
Hi,

Closing as it's being handled upstream.
