### ISSUE TITLE
Not compatible with phpunit 10.4.0

### ISSUE THREAD

**Issue by Tofandel** [symfony/panther#608]
It seems the latest version of phpunit included some changes affecting panther

```txt
Exception in third-party event subscriber: Too few arguments to function Symfony\Component\Panther\ServerExtensionLegacy::executeBeforeTest(), 0 passed in /vendor/symfony/panther/src/ServerExtension.php on line 81 and exactly 1 expected
```

It only occurs with 10.4.0, but I'm not sure it's comming directly from phpunit, it might be coming from #589 
https://github.com/symfony/panther/blob/2ef4eda403bd0841f31670e3b2f2a96f50b66dd4/src/ServerExtension.php#L81

https://github.com/symfony/panther/blob/2ef4eda403bd0841f31670e3b2f2a96f50b66dd4/src/ServerExtensionLegacy.php#L41

**Comment by shakaran** [comment]
I am getting this same error using pestphp/pest from 2.20.0 to 2.23.2 with Symfony 6.3

**Comment by janklan** [comment]
Do changes in https://github.com/symfony/panther/pull/609 fix it for you? They did for me.

**Comment by shakaran** [comment]
Testing with:

`composer require symfony/panther:dev-main`

I can confirm that perfectly works.

Could you make or bump a release tag for avoid to use directly main o a specific commit?

**Comment by janklan** [comment]
That's a question for @dunglas.

**Comment by GALPR** [comment]
@dunglas Any update on this? I am running into the same issue.

**Comment by driehle** [comment]
@GALPR Release 2.1.1 fixes the issues for me. See my comment [here](https://github.com/symfony/panther/issues/612#issuecomment-1842487238).

I think this ticket can be closed.
