### ISSUE TITLE
example for clicking on an alert box

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panther#62]
I think it'd be useful to have an alert box triggered in an example with the brief code of how to accept / dismiss it:

```
$client->switchTo()->alert()->accept();
```

**Comment by dunglas** [comment]
You would mind opening a docs PR?

**Comment by ChangePlaces** [comment]
i don't use panther now, there's too much that needs 'fixing' for it to be real-world useful imo.

**Comment by nicolas-grekas** [comment]
Please keep comments constructive.
Closing as there is no need to keep track.
PR welcome from anyone who would like to take the time to help this happen.
