### ISSUE TITLE
feature request: some shorthand way to retrieve input values?

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panther#63]
Getting the value of inputs is fairly common: `$crawler->filter('#course_title')->attr('value')` is perhaps a little long-winded. Could a helper function like `$crawler->filter('#foo')->value()` be more appropriate? Or even something shorter like `$crawler->input('#foo')->val()`?

**Comment by stof** [comment]
The DomCrawler component is not part of Panther, so this is the wrong place to ask for it.
