### ISSUE TITLE
Response object is not typed, and not allowing access to status code

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panther#64]
`$client->getResponse()->getStatusCode` is invalid as `getResponse` returns an object. I'm confused, does the `getResponse` function have to be wrapped inside PantherClient?

**Comment by stof** [comment]
`BrowserKit\Client::getResponse` is *never* typed to anything else than `object` (for legacy reasons...). Each BrowserKit implementation can return a different response object there.

- the HttpKernel one returns the HttpFoundation object which was returned by the kernel
- the Goutte one returns the BrowserKit Response object (same than for `getInternalResponse`, which always returns it)
