### ISSUE TITLE
client->wait is really client->maxtimeout

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panther#65]
I've been using `$client->wait(10)` as a sleep, thinking, it'll wait for x seconds, right? Except it doesn't. Digging through the code, it's a max time out for an operation rather than a wait:
```
     *   $driver->wait(20, 1000)->until(
     *     WebDriverExpectedCondition::titleIs('WebDriver Page')
     *   );
```
Can this be renamed, or perhaps made a little clearer somehow? Maybe passing the until condition as a closure to the wait method?

**Comment by stof** [comment]
that is exposing the `WebDriver::wait` method, expecting to use `->wait()->until()`.

That method is *not* documenting as being sleeping only (which would make no sense to do through webdriver)
