### ISSUE TITLE
Is Josh K's seal of approval still necessary?

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panther#66]
`if ($_SERVER['PANTHER_NO_SANDBOX'] ?? $_SERVER['HAS_JOSH_K_SEAL_OF_APPROVAL'] ?? false)`

I don't know a JoshK to ask for his seal of approval :( Should this be removed?

(Sorry for all these issues - I'm working on writing lots of e2e tests at the moment!)

**Comment by stof** [comment]
that's a way to detect whether we are running in Travis (as said in the comment on the line just before the one you copy-pasted), to disable the sandbox automatically on Travis (as it cannot run in sandbox mode there due to their own setup)

**Comment by nicolas-grekas** [comment]
Here is the link to source:
https://github.com/symfony/panther/blob/29cd7655c47acc0a398aba1558590b2e1cf41e34/src/ProcessManager/ChromeManager.php#L88

Closing as explained.
