### ISSUE TITLE
typo in packagist description

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panther#69]
> A browser testing and web __scrapping__ library for PHP and Symfony.

scrapping should be "scraping"

**Comment by stof** [comment]
would you mind sending a PR updating the composer.json ? This way, you would get authorship

**Comment by ChangePlaces** [comment]
should I close this issue, or will it automatically close when merged?

**Comment by stof** [comment]
I would put `Fixes #...` in the description of the PR, it gets closed automatically.

**Comment by ChangePlaces** [comment]
Thanks, I got there in the end!
