### ISSUE TITLE
take screenshot of failed assertions

### ISSUE THREAD

**Issue by ChangePlaces** [symfony/panther#73]
When a failed assertion occurs, how about saving the screen with the current timestamp?

**Comment by dunglas** [comment]
Would be great! Do you want to work on this?

**Comment by ChangePlaces** [comment]
panther has no use for me now!

**Comment by nicolas-grekas** [comment]
Closing then, no need to keep a wish list.

**Comment by javiereguiluz** [comment]
@ChangePlaces I don't know you, so maybe there's a language barrier issue (or maybe you are native English person, I don't know) but I'd like you to please publish more gentle comments.

This is an open source project, so the work is volunteered by people. Comments like this one or the others you published (https://github.com/symfony/panther/issues/60#issuecomment-42098, https://github.com/symfony/panther/issues/62#issuecomment-420989339) don't help at all to the project. Thanks a lot!
