### ISSUE TITLE
Symfony 3.4 support

### ISSUE THREAD

**Issue by emodric** [symfony/panther#79]
Hi,

is there a specific reason why Panther requires `symfony/browser-kit` and `symfony/console` in `^4.0` version?

Since Symfony 4.0 does not yet have an LTS version, and since it is fully compatible with 3.4, it would be nice to allow installing Panther with Symfony 3.4 present.

Thanks!

**Comment by dunglas** [comment]
Would you mind opening a PR lowering the requirements?

**Comment by emodric** [comment]
@dunglas Done in #82

**Comment by emodric** [comment]
Sadly, doesn't work with 3.4 :(
