### ISSUE TITLE
waitFor never find element

### ISSUE THREAD

**Issue by vasilvestre** [symfony/panther#91]
I'm using waitFor('.wai_hidden'), the page fail to load after a while
If I use wait(5) then $crawler->html(), there's an element with class=wai_hidden

**Comment by stof** [comment]
`waitFor` is waiting for a *visible* element matching the selector. The class name you're using makes me think it might not be visible.

**Comment by vasilvestre** [comment]
Or look like it doesn't work.. i try it again

**Comment by vasilvestre** [comment]
I don't need to scrap anymore, I close this.
