### ISSUE TITLE
Allow to set value on an input without using form

### ISSUE THREAD

**Issue by vasilvestre** [symfony/panther#92]
I got a real case, on this website there's no form but an ajax call launched when I put value in this input.
But I can't use ->form() as there's no form.

Is setValue on element possible ?

**Comment by dunglas** [comment]
Yes it is, using WebDriver directly yes. But providing a convenience method for that would be a nice addition!

**Comment by vasilvestre** [comment]
I already tried and failed hard. But if someone can create the method..

**Comment by npotier** [comment]
For the record :

```
$myInput = $crawler->filter('input[id=my_input]');
$myInput->sendKeys('I want to fill that input without the form() method');
```

**Comment by vasilvestre** [comment]
I should close my PR so  ? :)
