### ISSUE TITLE
Custom chrome path

### ISSUE THREAD

**Issue by Gemorroj** [symfony/panther#93]
How to set custom chrome binary path?

**Comment by dunglas** [comment]
Yes. Use the `PANTHER_CHROME_DRIVER_BINARY` env var: https://github.com/symfony/panther#environment-variables

**Comment by stof** [comment]
@dunglas that is changing the chromedriver binary, not the chrome binary

**Comment by Gemorroj** [comment]
I think we should do something similar, like in this pull request: https://github.com/symfony/panther/pull/77

**Comment by dunglas** [comment]
Oops I read too fast. Yes #77 looks almost good, I don't know why @Hakadel closed it.

**Comment by Hakadel** [comment]
@Gemorroj @dunglas Sorry the #77 was a test, but it works.

I opened a new one here : #96

Feel free to test it and/or merge it.

**Comment by Gemorroj** [comment]
resolved by #96
