### ISSUE TITLE
Add the support of "router" script to WebServerManager

### ISSUE THREAD

**Issue by maidmaid** [symfony/panther#98]
> If a PHP file is given on the command line when the web server is started it is treated as a "router" script. The script is run at the start of each HTTP request. 

http://php.net/manual/en/features.commandline.webserver.php

Basically, we could add a router param to `createPantherClient()` method. 

```php
protected static function createPantherClient(
    string $hostname = '127.0.0.1',
    int $port = 9000,
    string $router = null
): PantherClient
```

If you are interested, I can suggest a PR.

**Comment by dunglas** [comment]
👍 for this!
